"use client";

import {useMemo, useState} from "react";

type Presentation={label:string;concentration:number;unit:"mL"|"gota"|"comprimido"|"sachê"|"jato";note:string};
type Regimen={label:string;age:"Adulto"|"Pediatria";doseMin:number;doseMax:number;interval:string;maxDose?:number;maxDay?:string;presentations:Presentation[];note?:string;weightBased?:boolean};
type Medication={id:string;name:string;aliases:string[];use:string;tone:string;regimens:Regimen[];alerts:string[];sources:string[];referenceUrl?:string};

const medications:Medication[]=[
  {id:"dipirona",name:"Dipirona",aliases:["metamizol","novalgina","analgésico","antitérmico"],use:"Dor e febre",tone:"coral",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:500,doseMax:1000,interval:"a cada 4–6 h, se necessário",maxDay:"4 g/dia",presentations:[{label:"Solução 50 mg/mL",concentration:50,unit:"mL",note:"volume por dose"},{label:"Comprimido 500 mg",concentration:500,unit:"comprimido",note:"comprimidos por dose"}]},
    {label:"VO — pediatria",age:"Pediatria",doseMin:15,doseMax:25,interval:"a cada 6 h",maxDose:1000,maxDay:"respeitar máximo por peso/idade",presentations:[{label:"Gotas 500 mg/mL",concentration:25,unit:"gota",note:"25 mg por gota"},{label:"Solução 50 mg/mL",concentration:50,unit:"mL",note:"volume por dose"}]},
    {label:"EV — pediatria",age:"Pediatria",doseMin:15,doseMax:25,interval:"a cada 6 h",maxDose:1000,presentations:[{label:"Ampola 500 mg/mL",concentration:500,unit:"mL",note:"diluir em 10 mL de AD; administrar lentamente"}]},
  ],alerts:["Não usar AINEs, incluindo ibuprofeno, quando houver suspeita de dengue; dipirona e paracetamol são as opções do protocolo do MS.","Confirmar alergia prévia e apresentação antes de converter mg em mL ou gotas."],sources:["Referência pediátrica, fev/2024, p. 20","Guia rápido de prescrições para o plantão, p. 22","Ministério da Saúde — Dengue: diagnóstico e manejo clínico, 2024"],referenceUrl:"https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/dengue/dengue-diagnostico-e-manejo-clinico-adulto-e-crianca/view"},
  {id:"paracetamol",name:"Paracetamol",aliases:["acetaminofeno","tylenol","analgésico","antitérmico"],use:"Dor e febre",tone:"amber",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:500,doseMax:1000,interval:"a cada 4–6 h, se necessário",maxDay:"4 g/dia",presentations:[{label:"Comprimido 500 mg",concentration:500,unit:"comprimido",note:"comprimidos por dose"},{label:"Solução 100 mg/mL",concentration:100,unit:"mL",note:"volume por dose"}]},
    {label:"VO — pediatria",age:"Pediatria",doseMin:10,doseMax:15,interval:"a cada 4–6 h",maxDay:"máximo 5 doses/24 h",presentations:[{label:"Gotas 200 mg/mL",concentration:10,unit:"gota",note:"10 mg por gota"},{label:"Solução 160 mg/5 mL",concentration:32,unit:"mL",note:"32 mg/mL"},{label:"Solução 100 mg/mL",concentration:100,unit:"mL",note:"volume por dose"}]},
  ],alerts:["Somar o paracetamol presente em associações para não ultrapassar o limite diário.","Reduzir o teto diário em hepatopatia, baixo peso, desnutrição ou uso crônico de álcool."],sources:["Referência pediátrica, fev/2024, pp. 20–21","Guia rápido de prescrições para o plantão, p. 22","Ministério da Saúde — Dengue: diagnóstico e manejo clínico, 2024"],referenceUrl:"https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/dengue/dengue-diagnostico-e-manejo-clinico-adulto-e-crianca/view"},
  {id:"ibuprofeno",name:"Ibuprofeno",aliases:["alivium","anti-inflamatório","aine"],use:"Dor, febre e inflamação",tone:"blue",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:300,doseMax:600,interval:"a cada 8 h, se necessário",maxDay:"1.800 mg/dia",presentations:[{label:"Comprimido 300 mg",concentration:300,unit:"comprimido",note:"1–2 comprimidos por dose"},{label:"Comprimido 600 mg",concentration:600,unit:"comprimido",note:"até 1 comprimido por dose"}]},
    {label:"VO — pediatria",age:"Pediatria",doseMin:4,doseMax:10,interval:"a cada 6–8 h",maxDose:400,maxDay:"40 mg/kg/dia",presentations:[{label:"Gotas 50 mg/mL",concentration:5,unit:"gota",note:"5 mg por gota"},{label:"Gotas 100 mg/mL",concentration:10,unit:"gota",note:"10 mg por gota"},{label:"Gotas 200 mg/mL",concentration:20,unit:"gota",note:"20 mg por gota"}]},
  ],alerts:["Não usar na suspeita de dengue.","Evitar em desidratação, lesão renal, sangramento digestivo ou hipersensibilidade a AINE."],sources:["Referência pediátrica, fev/2024, p. 20","Guia rápido de prescrições para o plantão, p. 22"],referenceUrl:"https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/dengue/dengue-diagnostico-e-manejo-clinico-adulto-e-crianca/view"},
  {id:"ondansetrona",name:"Ondansetrona",aliases:["vonau","zofran","antiemético","náusea","vômito"],use:"Náuseas e vômitos",tone:"violet",regimens:[
    {label:"EV — adulto",age:"Adulto",doseMin:4,doseMax:8,interval:"a cada 8 h",presentations:[{label:"Ampola 2 mg/mL",concentration:2,unit:"mL",note:"diluir a dose em 10 mL de SF 0,9%; administrar lentamente"}]},
    {label:"VO — adulto",age:"Adulto",doseMin:8,doseMax:8,interval:"a cada 12 h por até 5 dias",presentations:[{label:"Comprimido 8 mg",concentration:8,unit:"comprimido",note:"1 comprimido por dose"}]},
    {label:"EV — pediatria",age:"Pediatria",doseMin:.15,doseMax:.15,interval:"por dose",maxDose:8,presentations:[{label:"Ampola 2 mg/mL",concentration:2,unit:"mL",note:"volume antes da rediluição"}],note:"A indicação muda o esquema. Para gastroenterite com vômitos persistentes, o MS usa dose única por faixa de peso."},
    {label:"VO — gastroenterite",age:"Pediatria",doseMin:0,doseMax:0,interval:"dose única",presentations:[],note:"6 meses–2 anos: 2 mg · >2–10 anos e até 30 kg: 4 mg · >10 anos ou >30 kg: 8 mg."},
  ],alerts:["Avaliar QT longo, distúrbios eletrolíticos e associação com outros fármacos que prolongam QT.","Não confundir a dose EV por peso com a dose única por faixa usada na reidratação oral."],sources:["Referência pediátrica, fev/2024, p. 23","Ministério da Saúde — Manejo do paciente com diarreia"],referenceUrl:"https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/doencas-diarreicas-agudas/manejo-do-paciente-com-diarreia-avaliacao-do-estado-do-paciente"},
  {id:"nitazoxanida",name:"Nitazoxanida",aliases:["annita","antiparasitário","giardíase","criptosporidíase"],use:"Protozoários e helmintos",tone:"blue",regimens:[
    {label:"VO — pediatria ≥1 ano",age:"Pediatria",doseMin:7.5,doseMax:7.5,interval:"a cada 12 h por 3 dias",maxDose:300,presentations:[{label:"Suspensão 20 mg/mL",concentration:20,unit:"mL",note:"máximo 15 mL por dose"}]},
    {label:"VO — ≥12 anos",age:"Adulto",doseMin:500,doseMax:500,interval:"a cada 12 h por 3 dias",presentations:[{label:"Comprimido 500 mg",concentration:500,unit:"comprimido",note:"1 comprimido por dose"}]},
  ],alerts:["O esquema e a duração mudam na criptosporidíase de imunodeprimidos."],sources:["Referência pediátrica, fev/2024, p. 19"]},
  {id:"secnidazol",name:"Secnidazol",aliases:["antiparasitário","amebíase","giardíase"],use:"Amebíase e giardíase",tone:"blue",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:2000,doseMax:2000,interval:"dose única",maxDose:2000,presentations:[{label:"Comprimido 500 mg",concentration:500,unit:"comprimido",note:"4 comprimidos em dose única"},{label:"Comprimido 1.000 mg",concentration:1000,unit:"comprimido",note:"2 comprimidos em dose única"}]},
    {label:"VO — dose única",age:"Pediatria",doseMin:30,doseMax:30,interval:"dose única",maxDose:2000,presentations:[{label:"Suspensão 30 mg/mL",concentration:30,unit:"mL",note:"equivale a 1 mL/kg"},{label:"Comprimido 500 mg",concentration:500,unit:"comprimido",note:"máximo 2 g"}]},
  ],alerts:["Amebíase hepática usa a mesma dose diária por 5–7 dias, não dose única."],sources:["Referência pediátrica, fev/2024, p. 19"]},
  {id:"cetoprofeno",name:"Cetoprofeno",aliases:["profenid","aine","analgésico","anti-inflamatório"],use:"Dor e inflamação",tone:"amber",regimens:[
    {label:"EV — adulto",age:"Adulto",doseMin:50,doseMax:100,interval:"a cada 8 h",maxDay:"400 mg/dia",presentations:[{label:"Ampola 100 mg/2 mL",concentration:50,unit:"mL",note:"diluir a dose em 100 mL de SF 0,9%; correr em 20 min"}]},
    {label:"VO — pediatria",age:"Pediatria",doseMin:1,doseMax:1,interval:"a cada 6–8 h",maxDose:100,presentations:[{label:"Gotas 20 mg/mL",concentration:1,unit:"gota",note:"1 mg por gota"}]},
    {label:"EV — pediatria",age:"Pediatria",doseMin:1,doseMax:1,interval:"por dose",maxDose:100,presentations:[{label:"Ampola 50 mg/mL",concentration:50,unit:"mL",note:"diluir em 50–100 mL de SF 0,9%; correr em 30 min"}]},
  ],alerts:["Evitar na suspeita de dengue, desidratação, lesão renal ou sangramento digestivo."],sources:["Referência pediátrica, fev/2024, p. 20"]},
  {id:"morfina",name:"Morfina",aliases:["opioide","analgesia","dor intensa"],use:"Dor intensa",tone:"violet",regimens:[
    {label:"EV — adulto, titulação",age:"Adulto",doseMin:3,doseMax:3,interval:"a cada 15 min até analgesia",maxDay:"15 mg na primeira hora",presentations:[{label:"Solução rediluída 1 mg/mL",concentration:1,unit:"mL",note:"ampola 10 mg/mL: aspirar 1 mL e completar para 10 mL com AD"}],note:"Administrar 3 mL por etapa e reavaliar dor, sedação e ventilação antes de repetir."},
    {label:"EV/IM/SC — pediatria",age:"Pediatria",doseMin:.1,doseMax:.1,interval:"a cada 4 h, titulando à resposta",presentations:[{label:"Solução rediluída 1 mg/mL",concentration:1,unit:"mL",note:"se ampola 10 mg/mL: 1 mL + 9 mL de AD"}]},
  ],alerts:["Monitorizar ventilação, sedação e pressão; ter estratégia para depressão respiratória.","A concentração original de 10 mg/mL exige rediluição antes deste cálculo."],sources:["Referência pediátrica, fev/2024, p. 20"]},
  {id:"tramadol",name:"Tramadol",aliases:["tramal","opioide","analgesia"],use:"Dor moderada a intensa",tone:"violet",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:50,doseMax:100,interval:"a cada 6 h",maxDay:"400 mg/dia",presentations:[{label:"Cápsula 50 mg",concentration:50,unit:"comprimido",note:"1–2 unidades por dose"}]},
    {label:"EV — adulto",age:"Adulto",doseMin:50,doseMax:100,interval:"a cada 6 h",maxDay:"400 mg/dia",presentations:[{label:"Ampola 100 mg/2 mL",concentration:50,unit:"mL",note:"diluir a dose em 100 mL de SF 0,9%; correr em 30 min"}]},
    {label:"VO/EV — pediatria",age:"Pediatria",doseMin:1,doseMax:2,interval:"a cada 4–6 h",maxDose:100,maxDay:"400 mg/dia",presentations:[{label:"Gotas 100 mg/mL",concentration:2.5,unit:"gota",note:"2,5 mg por gota"},{label:"Ampola 50 mg/mL",concentration:50,unit:"mL",note:"EV: diluir em 50–100 mL de SF 0,9%; correr em 30 min"}]},
  ],alerts:["Considerar risco de sedação, convulsão e síndrome serotoninérgica."],sources:["Referência pediátrica, fev/2024, p. 21"]},
  {id:"dimenidrinato",name:"Dimenidrinato",aliases:["dramin","antiemético","náusea","vômito"],use:"Náuseas e vômitos",tone:"coral",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:50,doseMax:100,interval:"a cada 4–6 h",presentations:[{label:"Comprimido 100 mg",concentration:100,unit:"comprimido",note:"0,5–1 comprimido por dose"},{label:"Gotas 25 mg/mL",concentration:1,unit:"gota",note:"1 mg por gota; 50–100 gotas por dose"}]},
    {label:"EV/IM — adulto",age:"Adulto",doseMin:50,doseMax:50,interval:"a cada 6 h",presentations:[{label:"Ampola 50 mg/mL",concentration:50,unit:"mL",note:"para infusão descrita: diluir 1 ampola em 250 mL de SF 0,9% e correr em 30 min"}],note:"A concentração varia entre apresentações comerciais; conferir a ampola antes de converter."},
    {label:"VO/EV/IM — pediatria",age:"Pediatria",doseMin:1,doseMax:1.5,interval:"a cada 6 h",presentations:[{label:"Gotas 25 mg/mL",concentration:1,unit:"gota",note:"1 mg por gota"},{label:"Ampola 50 mg/mL",concentration:50,unit:"mL",note:"confirmar via escolhida"}]},
  ],alerts:["Pode causar sedação e efeitos anticolinérgicos."],sources:["Referência pediátrica, fev/2024, p. 22"]},
  {id:"domperidona",name:"Domperidona",aliases:["motilium","antiemético","procinético"],use:"Náuseas e distúrbios de motilidade",tone:"coral",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:10,doseMax:10,interval:"a cada 8 h, 30 min antes das refeições",maxDay:"30 mg/dia neste esquema",presentations:[{label:"Comprimido 10 mg",concentration:10,unit:"comprimido",note:"1 comprimido por dose"}]},
    {label:"VO — pediatria",age:"Pediatria",doseMin:.25,doseMax:.4,interval:"a cada 8 h, antes das refeições",presentations:[{label:"Suspensão 1 mg/mL",concentration:1,unit:"mL",note:"volume por dose"}]},
  ],alerts:["Avaliar risco de prolongamento de QT e interações antes da prescrição.","Evitar associação com cetoconazol."],sources:["Referência pediátrica, fev/2024, p. 22","Plantão Prescrições, seção de náuseas e vômitos"]},
  {id:"bromoprida",name:"Bromoprida",aliases:["digesan","plamet","antiemético","procinético","náusea","vômito"],use:"Náuseas, vômitos e distúrbios de motilidade",tone:"coral",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:10,doseMax:10,interval:"a cada 8 h, 30 min antes das refeições",maxDay:"30 mg/dia neste esquema",presentations:[{label:"Comprimido 10 mg",concentration:10,unit:"comprimido",note:"1 comprimido por dose"}]},
    {label:"EV — adulto",age:"Adulto",doseMin:10,doseMax:10,interval:"a cada 8 h",maxDay:"30 mg/dia neste esquema",presentations:[{label:"Ampola 10 mg/2 mL",concentration:5,unit:"mL",note:"2 mL por dose; administrar lentamente"}]},
    {label:"VO — pediatria",age:"Pediatria",doseMin:.5/3,doseMax:1/3,interval:"a cada 8 h",presentations:[{label:"Gotas 4 mg/mL",concentration:.17,unit:"gota",note:"aprox. 0,17 mg/gota; regra prática: 1 gota/kg/dose"}],note:"Dose diária de 0,5–1 mg/kg dividida em 3 administrações."},
    {label:"EV — pediatria",age:"Pediatria",doseMin:.15,doseMax:.15,interval:"a cada 8 h",presentations:[{label:"Ampola 5 mg/mL",concentration:5,unit:"mL",note:"0,03 mL/kg/dose; completar para 20 mL com AD ou SF 0,9%"}]},
  ],alerts:["Observar sonolência e reações extrapiramidais, especialmente em crianças."],sources:["Referência pediátrica, fev/2024, p. 22","Guia rápido de prescrições para o plantão, p. 15","Plantão Prescrições, seção de náuseas e vômitos"]},
  {id:"racecadotrila",name:"Racecadotrila",aliases:["tiorfan","antissecretor","diarreia"],use:"Diarreia aguda",tone:"blue",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:100,doseMax:100,interval:"a cada 8 h, antes das refeições, por até 7 dias",maxDay:"300 mg/dia",presentations:[{label:"Cápsula 100 mg",concentration:100,unit:"comprimido",note:"1 cápsula por dose"}]},
    {label:"VO — pediatria ≥3 meses",age:"Pediatria",doseMin:1.5,doseMax:1.5,interval:"a cada 8 h; suspender quando cessar a diarreia",presentations:[{label:"Sachê 10 mg",concentration:10,unit:"sachê",note:"número teórico de sachês de 10 mg"},{label:"Sachê 30 mg",concentration:30,unit:"sachê",note:"número teórico de sachês de 30 mg"}]},
  ],alerts:["Não utilizar abaixo de 3 meses.","Reidratação oral permanece o tratamento central."],sources:["Referência pediátrica, fev/2024, p. 24"]},
  {id:"simeticona",name:"Simeticona",aliases:["luftal","gases","distensão abdominal"],use:"Meteorismo e desconforto por gases",tone:"amber",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:48,doseMax:48,interval:"a cada 8 h, se necessário",presentations:[{label:"Gotas 75 mg/mL",concentration:3,unit:"gota",note:"16 gotas por dose"}],note:"A concentração por gota varia conforme a marca."},
    {label:"VO — pediatria",age:"Pediatria",doseMin:1,doseMax:1,interval:"a cada 6 h",presentations:[{label:"Luftal gotas",concentration:3,unit:"gota",note:"3 mg por gota; outras marcas variam"}]},
  ],alerts:["A quantidade de mg por gota varia conforme a marca; selecionar apenas após conferir o frasco."],sources:["Referência pediátrica, fev/2024, p. 23"]},
  {id:"amoxicilina",name:"Amoxicilina",aliases:["amoxil","penicilina","antibiótico","otite","sinusite","pneumonia"],use:"Infecções bacterianas sensíveis",tone:"blue",regimens:[
    {label:"VO — adulto 500 mg",age:"Adulto",doseMin:500,doseMax:500,interval:"a cada 8 h por 7–14 dias, conforme indicação",maxDay:"1.500 mg/dia neste esquema",presentations:[{label:"Cápsula 500 mg",concentration:500,unit:"comprimido",note:"1 cápsula por dose"}]},
    {label:"VO — adulto 875 mg",age:"Adulto",doseMin:875,doseMax:875,interval:"a cada 12 h por 7–14 dias, conforme indicação",maxDay:"1.750 mg/dia neste esquema",presentations:[{label:"Comprimido 875 mg",concentration:875,unit:"comprimido",note:"1 comprimido por dose"}]},
    {label:"VO — pediatria, dose usual",age:"Pediatria",doseMin:50/3,doseMax:50/3,interval:"a cada 8 h",maxDay:"50 mg/kg/dia",presentations:[{label:"Suspensão 250 mg/5 mL",concentration:50,unit:"mL",note:"reconstituir até a marca do frasco; agitar antes de cada dose"},{label:"Suspensão 400 mg/5 mL",concentration:80,unit:"mL",note:"reconstituir até a marca do frasco; agitar antes de cada dose"}],note:"Conversão de 50 mg/kg/dia divididos em 3 doses."},
    {label:"VO — pediatria, dose alta",age:"Pediatria",doseMin:80/3,doseMax:90/3,interval:"a cada 8 h",maxDay:"90 mg/kg/dia",presentations:[{label:"Suspensão 250 mg/5 mL",concentration:50,unit:"mL",note:"reconstituir até a marca do frasco; agitar antes de cada dose"},{label:"Suspensão 400 mg/5 mL",concentration:80,unit:"mL",note:"reconstituir até a marca do frasco; agitar antes de cada dose"}],note:"Dose alta reservada às indicações descritas no protocolo."},
  ],alerts:["Escolha de dose e duração depende do foco, gravidade, idade e diagnóstico bacteriano.","Confirmar alergia imediata a penicilinas e ajustar intervalo na disfunção renal."],sources:["Referência pediátrica, fev/2024, p. 7","Plantão Prescrições, pp. 5–10 e seção de antimicrobianos"]},
  {id:"amoxicilina-clavulanato",name:"Amoxicilina + clavulanato",aliases:["clavulin","sinot-clav","atak clav","antibiótico","otite","sinusite"],use:"Infecções bacterianas com indicação de inibidor de betalactamase",tone:"blue",regimens:[
    {label:"VO — adulto 500/125 mg",age:"Adulto",doseMin:500,doseMax:500,interval:"a cada 8 h por 7–10 dias, conforme indicação",maxDay:"1.500 mg/dia de amoxicilina",presentations:[{label:"Comprimido 500/125 mg",concentration:500,unit:"comprimido",note:"1 comprimido por dose; cálculo expresso pelo componente amoxicilina"}]},
    {label:"VO — adulto 875/125 mg",age:"Adulto",doseMin:875,doseMax:875,interval:"a cada 12 h por 7–10 dias, conforme indicação",maxDay:"1.750 mg/dia de amoxicilina",presentations:[{label:"Comprimido 875/125 mg",concentration:875,unit:"comprimido",note:"1 comprimido por dose; cálculo expresso pelo componente amoxicilina"}]},
    {label:"VO — pediatria 8/8 h",age:"Pediatria",doseMin:50/3,doseMax:50/3,interval:"a cada 8 h",maxDay:"50 mg/kg/dia de amoxicilina",presentations:[{label:"Suspensão 250/62,5 mg em 5 mL",concentration:50,unit:"mL",note:"reconstituir até a marca; agitar; cálculo pelo componente amoxicilina"}]},
    {label:"VO — pediatria BD",age:"Pediatria",doseMin:25,doseMax:25,interval:"a cada 12 h",maxDay:"50 mg/kg/dia de amoxicilina",presentations:[{label:"Suspensão 400/57 mg em 5 mL",concentration:80,unit:"mL",note:"reconstituir até a marca; agitar; cálculo pelo componente amoxicilina"}]},
  ],alerts:["Não intercambiar suspensões apenas pelo volume: a proporção de clavulanato varia.","Administrar no início da refeição e ajustar intervalo na disfunção renal."],sources:["Referência pediátrica, fev/2024, p. 7","Plantão Prescrições, seções de sinusite, otite e pneumonia"]},
  {id:"azitromicina",name:"Azitromicina",aliases:["zitromax","astro","macrolídeo","antibiótico","atípicos"],use:"Infecções bacterianas com indicação de macrolídeo",tone:"blue",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:500,doseMax:500,interval:"a cada 24 h por 3–5 dias, conforme indicação",maxDay:"500 mg/dia",presentations:[{label:"Comprimido 500 mg",concentration:500,unit:"comprimido",note:"1 comprimido por dose"}]},
    {label:"VO — adulto, dose única",age:"Adulto",doseMin:1000,doseMax:1000,interval:"dose única, somente nas indicações específicas",maxDose:1000,presentations:[{label:"Comprimido 500 mg",concentration:500,unit:"comprimido",note:"2 comprimidos em dose única"}]},
    {label:"VO — pediatria, usual",age:"Pediatria",doseMin:10,doseMax:10,interval:"a cada 24 h",maxDose:500,maxDay:"500 mg/dia",presentations:[{label:"Suspensão 200 mg/5 mL",concentration:40,unit:"mL",note:"reconstituir até a marca; agitar antes de cada dose"}]},
    {label:"VO — pediatria, atípicos",age:"Pediatria",doseMin:20,doseMax:20,interval:"a cada 24 h",maxDose:1200,maxDay:"1.200 mg/dia",presentations:[{label:"Suspensão 200 mg/5 mL",concentration:40,unit:"mL",note:"reconstituir até a marca; agitar antes de cada dose"}],note:"Esquema de dose alta descrito para bactérias atípicas."},
  ],alerts:["Não usar automaticamente para quadros virais.","Avaliar prolongamento de QT, hepatopatia e interações relevantes."],sources:["Referência pediátrica, fev/2024, p. 7","Guia rápido de prescrições para o plantão, pp. 17–22","Plantão Prescrições, seção de antimicrobianos"]},
  {id:"cefalexina",name:"Cefalexina",aliases:["keflex","cefalosporina","antibiótico","pele","impetigo","celulite"],use:"Infecções bacterianas sensíveis, especialmente pele e tecidos moles",tone:"blue",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:500,doseMax:500,interval:"a cada 6 h por 7–10 dias, conforme indicação",maxDay:"2.000 mg/dia neste esquema",presentations:[{label:"Cápsula 500 mg",concentration:500,unit:"comprimido",note:"1 cápsula por dose"}]},
    {label:"VO — pediatria",age:"Pediatria",doseMin:12.5,doseMax:12.5,interval:"a cada 6 h",maxDay:"50 mg/kg/dia",presentations:[{label:"Suspensão 250 mg/5 mL",concentration:50,unit:"mL",note:"reconstituir até a marca; agitar antes de cada dose"}],note:"Conversão de 50 mg/kg/dia divididos em 4 doses."},
  ],alerts:["Duração e adequação dependem do foco e da gravidade.","Investigar reação imediata grave a betalactâmicos e ajustar na disfunção renal."],sources:["Referência pediátrica, fev/2024, p. 8","Plantão Prescrições, seções de pele e antimicrobianos"]},
  {id:"metronidazol",name:"Metronidazol",aliases:["flagyl","anaeróbios","giardíase","amebíase","tricomoníase","vaginose"],use:"Infecções por anaeróbios e protozoários",tone:"blue",regimens:[
    {label:"VO — adulto, anaeróbios",age:"Adulto",doseMin:400,doseMax:400,interval:"a cada 8 h; duração conforme foco",maxDay:"1.200 mg/dia neste esquema",presentations:[{label:"Comprimido 400 mg",concentration:400,unit:"comprimido",note:"1 comprimido por dose"}]},
    {label:"EV — adulto",age:"Adulto",doseMin:500,doseMax:500,interval:"a cada 8 h; duração conforme foco",maxDay:"1.500 mg/dia",presentations:[{label:"Frasco 500 mg/100 mL",concentration:5,unit:"mL",note:"100 mL por dose; solução pronta para infusão em aproximadamente 1 h"}]},
    {label:"VO/EV — pediatria",age:"Pediatria",doseMin:10,doseMax:40/3,interval:"a cada 8 h",maxDay:"30–40 mg/kg/dia; máximo 1.500 mg/dia",presentations:[{label:"Suspensão 40 mg/mL",concentration:40,unit:"mL",note:"agitar antes de cada dose"},{label:"Solução EV 5 mg/mL",concentration:5,unit:"mL",note:"infundir em aproximadamente 1 h"}],note:"Conversão de 30–40 mg/kg/dia divididos em 3 doses."},
  ],alerts:["A dose e a duração mudam entre anaeróbios, giardíase, amebíase, tricomoníase e vaginose.","Evitar álcool durante o tratamento e por pelo menos 48 h após a última dose."],sources:["Referência pediátrica, fev/2024, quadro de antimicrobianos e p. 12","Plantão Prescrições, seções de parasitoses e antimicrobianos"]},
  {id:"loratadina",name:"Loratadina",aliases:["claritin","anti-histamínico","alergia","rinite","urticária"],use:"Sintomas alérgicos",tone:"coral",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:10,doseMax:10,interval:"a cada 24 h",maxDay:"10 mg/dia",presentations:[{label:"Comprimido 10 mg",concentration:10,unit:"comprimido",note:"1 comprimido por dose"},{label:"Xarope 1 mg/mL",concentration:1,unit:"mL",note:"10 mL por dose"}]},
    {label:"VO — 6 meses a <2 anos",age:"Pediatria",weightBased:false,doseMin:2.5,doseMax:2.5,interval:"a cada 24 h",maxDay:"2,5 mg/dia",presentations:[{label:"Xarope 1 mg/mL",concentration:1,unit:"mL",note:"2,5 mL por dose"}],note:"Evitar o uso rotineiro abaixo de 2 anos."},
    {label:"VO — 2 a 5 anos",age:"Pediatria",weightBased:false,doseMin:5,doseMax:5,interval:"a cada 24 h",maxDay:"5 mg/dia",presentations:[{label:"Xarope 1 mg/mL",concentration:1,unit:"mL",note:"5 mL por dose"}]},
    {label:"VO — ≥6 anos ou >30 kg",age:"Pediatria",weightBased:false,doseMin:10,doseMax:10,interval:"a cada 24 h",maxDay:"10 mg/dia",presentations:[{label:"Xarope 1 mg/mL",concentration:1,unit:"mL",note:"10 mL por dose"},{label:"Comprimido 10 mg",concentration:10,unit:"comprimido",note:"1 comprimido por dose"}]},
  ],alerts:["A ficha por faixa etária não usa o peso para multiplicar a dose.","O próprio guia pediátrico registra cautela/evitar em menores de 2 anos."],sources:["Referência pediátrica, fev/2024, p. 26","Guia rápido de prescrições para o plantão, p. 22","Plantão Prescrições, seção de alergias"]},
  {id:"dexclorfeniramina",name:"Dexclorfeniramina",aliases:["polaramine","anti-histamínico","alergia","urticária","prurido"],use:"Sintomas alérgicos e prurido",tone:"coral",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:2,doseMax:2,interval:"a cada 6–8 h",maxDay:"12 mg/dia",presentations:[{label:"Comprimido 2 mg",concentration:2,unit:"comprimido",note:"1 comprimido por dose"},{label:"Solução 0,4 mg/mL",concentration:.4,unit:"mL",note:"5 mL por dose"}]},
    {label:"VO — 2 a 6 anos",age:"Pediatria",weightBased:false,doseMin:.5,doseMax:.5,interval:"a cada 8 h",maxDay:"1,5 mg/dia",presentations:[{label:"Solução 0,4 mg/mL",concentration:.4,unit:"mL",note:"1,25 mL por dose"},{label:"Gotas 2,8 mg/mL",concentration:.1,unit:"gota",note:"5 gotas por dose"}]},
    {label:"VO — 6 a 12 anos",age:"Pediatria",weightBased:false,doseMin:1,doseMax:1,interval:"a cada 8 h",maxDay:"3 mg/dia",presentations:[{label:"Comprimido 2 mg",concentration:2,unit:"comprimido",note:"meio comprimido por dose"},{label:"Solução 0,4 mg/mL",concentration:.4,unit:"mL",note:"2,5 mL por dose"},{label:"Gotas 2,8 mg/mL",concentration:.1,unit:"gota",note:"10 gotas por dose"}]},
  ],alerts:["Pode causar sedação e efeitos anticolinérgicos.","Não utilizar esta ficha pediátrica abaixo de 2 anos."],sources:["Referência pediátrica, fev/2024, p. 26","Guia rápido de prescrições para o plantão, p. 30"]},
  {id:"salbutamol",name:"Salbutamol",aliases:["aerolin","broncodilatador","asma","broncoespasmo","sibilância"],use:"Broncoespasmo e exacerbação asmática",tone:"violet",regimens:[
    {label:"Inalatória — adulto, aerossol",age:"Adulto",doseMin:.4,doseMax:.8,interval:"a cada 20 min na primeira hora; depois conforme resposta",maxDose:.8,presentations:[{label:"Aerossol 100 mcg/jato",concentration:.1,unit:"jato",note:"4–8 jatos com espaçador por dose"}]},
    {label:"Nebulização — adulto",age:"Adulto",doseMin:2.5,doseMax:5,interval:"a cada 20 min por 3 doses",maxDose:5,presentations:[{label:"Solução 5 mg/mL",concentration:5,unit:"mL",note:"0,5–1 mL; completar com SF 0,9% conforme nebulizador"}]},
    {label:"Nebulização — pediatria",age:"Pediatria",doseMin:.07,doseMax:.15,interval:"a cada 20 min por até 3 doses",maxDose:5,presentations:[{label:"Solução 5 mg/mL",concentration:5,unit:"mL",note:"diluir em SF 0,9% conforme o volume operacional do nebulizador"}]},
  ],alerts:["Reavaliar frequência cardíaca, esforço respiratório, ausculta e saturação após cada ciclo.","Tremor e taquicardia são efeitos dose-dependentes."],sources:["Protocolo hospitalar de asma — SES-SC, 2025","Fluxograma de crise de asma — SES-DF"],referenceUrl:"https://www.saude.sc.gov.br/index.php/pt/servicos/assistencia-farmaceutica-diaf/comissao-de-farmacia-e-terapeutica-cft/protocolo-de-uso-de-medicamentos-exclusivo-hospitais-da-ses-sc/protocolo-asma-hospitalar/download"},
  {id:"prednisona-prednisolona",name:"Prednisona / Prednisolona",aliases:["meticorten","prelone","corticoide","asma","alergia"],use:"Corticoterapia sistêmica de curta duração",tone:"amber",regimens:[
    {label:"VO — adulto, exacerbação asmática",age:"Adulto",doseMin:40,doseMax:60,interval:"uma vez ao dia por até 5–7 dias",maxDay:"60 mg/dia",presentations:[{label:"Prednisona 20 mg",concentration:20,unit:"comprimido",note:"2–3 comprimidos por dia"},{label:"Prednisona 5 mg",concentration:5,unit:"comprimido",note:"8–12 comprimidos por dia"}]},
    {label:"VO — pediatria",age:"Pediatria",doseMin:1,doseMax:2,interval:"uma vez ao dia ou dividida em 2 doses por 3–5 dias",maxDose:60,maxDay:"60 mg/dia",presentations:[{label:"Prednisolona 3 mg/mL",concentration:3,unit:"mL",note:"volume calculado por dose"},{label:"Prednisona 20 mg",concentration:20,unit:"comprimido",note:"usar quando a forma sólida for adequada"}]},
  ],alerts:["Usar o esquema da indicação selecionada; tratamentos prolongados exigem plano específico de redução.","Considerar glicemia, pressão arterial e risco infeccioso."],sources:["Protocolo hospitalar de asma — SES-SC, 2025","Fluxograma de crise de asma — SES-DF"],referenceUrl:"https://www.saude.sc.gov.br/index.php/pt/servicos/assistencia-farmaceutica-diaf/comissao-de-farmacia-e-terapeutica-cft/protocolo-de-uso-de-medicamentos-exclusivo-hospitais-da-ses-sc/protocolo-asma-hospitalar/download"},
  {id:"dexametasona",name:"Dexametasona",aliases:["decadron","corticoide","crupe","laringite","edema de glote"],use:"Crupe, edema de via aérea e outras indicações selecionadas",tone:"amber",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:.75,doseMax:9,interval:"dose diária conforme indicação e resposta",maxDay:"9 mg/dia neste esquema",presentations:[{label:"Comprimido 4 mg",concentration:4,unit:"comprimido",note:"selecionar dose dentro da faixa clínica"},{label:"Elixir 0,1 mg/mL",concentration:.1,unit:"mL",note:"volume calculado por dose"}]},
    {label:"IM/EV — pediatria, crupe",age:"Pediatria",doseMin:.6,doseMax:.6,interval:"dose única",maxDose:16,presentations:[{label:"Solução 4 mg/mL",concentration:4,unit:"mL",note:"não necessita diluição para o esquema descrito"}]},
    {label:"VO — pediatria, crupe leve",age:"Pediatria",doseMin:.15,doseMax:.3,interval:"dose única",maxDose:16,presentations:[{label:"Elixir 0,1 mg/mL",concentration:.1,unit:"mL",note:"volume pode ser elevado nesta concentração; conferir apresentação disponível"}]},
  ],alerts:["A dose varia amplamente conforme a indicação; selecionar o esquema correto antes do cálculo."],sources:["Referência pediátrica, fev/2024, seção de corticoides","Fluxograma de reação alérgica — SES-DF"],referenceUrl:"https://www.saude.df.gov.br/documents/37101/87400/Rea%C3%A7%C3%A3o%2BAl%C3%A9rgica%2B%E2%80%93%2BFluxograma.pdf/45ed768b-1b81-f9e3-2ddf-e9ac6354e2d0"},
  {id:"hidrocortisona",name:"Hidrocortisona",aliases:["flebocortid","corticoide","asma grave","insuficiência adrenal","alergia"],use:"Corticoterapia parenteral em situações selecionadas",tone:"amber",regimens:[
    {label:"EV — adulto",age:"Adulto",doseMin:200,doseMax:300,interval:"a cada 6 h, conforme indicação",presentations:[{label:"Frasco-ampola 100 mg",concentration:100,unit:"mL",note:"reconstituir conforme o fabricante; a concentração final depende do diluente"},{label:"Frasco-ampola 500 mg",concentration:500,unit:"mL",note:"reconstituir conforme o fabricante; a concentração final depende do diluente"}]},
    {label:"EV — pediatria, dose de ataque",age:"Pediatria",doseMin:4,doseMax:4,interval:"dose de ataque",maxDose:250,presentations:[{label:"Solução reconstituída 50 mg/mL",concentration:50,unit:"mL",note:"usar apenas se a reconstituição resultar em 50 mg/mL"}]},
  ],alerts:["Confirmar a concentração após a reconstituição antes de calcular o volume.","Não substitui adrenalina IM na anafilaxia."],sources:["Guia rápido de prescrições para o plantão, seção de anafilaxia","Protocolos de urgência — SES-DF"],referenceUrl:"https://www.saude.df.gov.br/documents/37101/0/Protocolos%2Bde%2BRegula%C3%A7%C3%A3o%2BM%C3%A9dica%2Bde%2BUrg%C3%AAncia%2Bdo%2BSAMU-%2BDF%2B192%2Be%2BCrit%C3%A9rios%2BM%C3%A9dicos%2Bde%2BDespacho%2Bde%2BViaturas.%2BPED.pdf/475a9405-50eb-be13-e9f1-356801c4eddb?t=1717432225608"},
  {id:"ceftriaxona",name:"Ceftriaxona",aliases:["rocefin","cefalosporina","antibiótico","pneumonia","meningite"],use:"Infecções bacterianas com indicação de cefalosporina parenteral",tone:"blue",regimens:[
    {label:"EV — adulto",age:"Adulto",doseMin:1000,doseMax:2000,interval:"a cada 24 h ou dividida a cada 12 h, conforme indicação",maxDay:"4 g/dia",presentations:[{label:"Solução reconstituída 100 mg/mL",concentration:100,unit:"mL",note:"rediluir para 40 mg/mL em SF 0,9%; infundir em 30 min"}]},
    {label:"EV — pediatria",age:"Pediatria",doseMin:50,doseMax:100,interval:"a cada 24 h ou dividida a cada 12 h",maxDose:4000,maxDay:"4 g/dia",presentations:[{label:"Solução reconstituída 100 mg/mL",concentration:100,unit:"mL",note:"rediluir para 40 mg/mL em SF 0,9%; infundir em 30 min"}],note:"Acima de 2 g/dia, dividir em duas administrações."},
  ],alerts:["Não misturar nem administrar simultaneamente com soluções contendo cálcio, especialmente em neonatos.","O esquema de meningite utiliza dose e fracionamento específicos."],sources:["Referência pediátrica, fev/2024, seção de antimicrobianos","Guia rápido de prescrições para o plantão, seção de pneumonia"]},
  {id:"clindamicina",name:"Clindamicina",aliases:["dalacin","lincosamida","antibiótico","anaeróbios","pele"],use:"Infecções por cocos gram-positivos e anaeróbios sensíveis",tone:"blue",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:300,doseMax:300,interval:"a cada 6 h por 7–14 dias, conforme indicação",maxDay:"1.800 mg/dia",presentations:[{label:"Cápsula 300 mg",concentration:300,unit:"comprimido",note:"1 cápsula por dose"}]},
    {label:"EV — adulto",age:"Adulto",doseMin:600,doseMax:600,interval:"a cada 8 h",maxDay:"1.800 mg/dia",presentations:[{label:"Ampola 150 mg/mL",concentration:150,unit:"mL",note:"4 mL por dose; rediluir para até 6 mg/mL e infundir em 30 min"}]},
    {label:"VO/EV — pediatria",age:"Pediatria",doseMin:25/4,doseMax:40/4,interval:"a cada 6 h",maxDose:450,maxDay:"1.800 mg/dia",presentations:[{label:"Ampola 150 mg/mL",concentration:150,unit:"mL",note:"EV: rediluir para até 6 mg/mL e infundir em 30 min"}],note:"Faixa de 25–40 mg/kg/dia dividida em 4 doses."},
  ],alerts:["Diarreia importante durante ou após o tratamento exige investigação de colite associada a antibiótico."],sources:["Referência pediátrica, fev/2024, seção de antimicrobianos","Guia rápido de prescrições para o plantão, pp. 17–22"]},
  {id:"fluconazol",name:"Fluconazol",aliases:["triazol","antifúngico","candidíase","criptococose","micose"],use:"Infecções fúngicas sensíveis",tone:"violet",regimens:[
    {label:"VO — adulto, candidíase vulvovaginal",age:"Adulto",doseMin:150,doseMax:150,interval:"dose única",maxDose:150,presentations:[{label:"Cápsula 150 mg",concentration:150,unit:"comprimido",note:"1 cápsula em dose única"}]},
    {label:"EV — pediatria, manutenção",age:"Pediatria",doseMin:3,doseMax:12,interval:"a cada 24 h",maxDose:800,maxDay:"400–800 mg/dia, conforme indicação",presentations:[{label:"Bolsa pronta 2 mg/mL",concentration:2,unit:"mL",note:"não diluir; infundir em 1–2 h"}],note:"Dose de ataque descrita: 6–12 mg/kg no primeiro dia."},
  ],alerts:["Dose, duração e necessidade de ataque variam conforme sítio, espécie e imunidade.","Ajustar na disfunção renal e revisar interações medicamentosas."],sources:["Referência pediátrica, fev/2024, seção de antifúngicos","Plantão Prescrições, seção de candidíase"]},
  {id:"albendazol",name:"Albendazol",aliases:["zentel","anti-helmíntico","verminose","parasitas"],use:"Helmintíases selecionadas",tone:"blue",regimens:[
    {label:"VO — adulto e ≥2 anos",age:"Adulto",doseMin:400,doseMax:400,interval:"a cada 24 h por 1–3 dias, conforme parasitose",maxDay:"400 mg/dia",presentations:[{label:"Comprimido 400 mg",concentration:400,unit:"comprimido",note:"1 comprimido por dose"},{label:"Suspensão 400 mg/10 mL",concentration:40,unit:"mL",note:"10 mL por dose; agitar"}]},
    {label:"VO — 1 a 2 anos",age:"Pediatria",weightBased:false,doseMin:200,doseMax:200,interval:"a cada 24 h por 3–5 dias, conforme indicação",maxDay:"200 mg/dia",presentations:[{label:"Suspensão 400 mg/10 mL",concentration:40,unit:"mL",note:"5 mL por dose; agitar"}]},
  ],alerts:["O esquema muda conforme o parasita; neurocisticercose e doença disseminada não usam esta ficha rápida.","Entre 1 e 2 anos, avaliar cuidadosamente indicação e benefício."],sources:["Referência pediátrica, fev/2024, seção de antiparasitários","Plantão Prescrições, seção de anti-helmínticos"]},
  {id:"mebendazol",name:"Mebendazol",aliases:["pantelmin","anti-helmíntico","verminose","parasitas"],use:"Helmintíases intestinais selecionadas",tone:"blue",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:100,doseMax:100,interval:"a cada 12 h por 3 dias",maxDay:"200 mg/dia",presentations:[{label:"Comprimido 100 mg",concentration:100,unit:"comprimido",note:"1 comprimido por dose"},{label:"Suspensão 100 mg/5 mL",concentration:20,unit:"mL",note:"5 mL por dose; agitar"}]},
    {label:"VO — pediatria ≥2 anos",age:"Pediatria",weightBased:false,doseMin:100,doseMax:100,interval:"a cada 12 h por 3 dias",maxDay:"200 mg/dia",presentations:[{label:"Suspensão 100 mg/5 mL",concentration:20,unit:"mL",note:"5 mL por dose; agitar"},{label:"Comprimido 100 mg",concentration:100,unit:"comprimido",note:"1 comprimido por dose"}]},
  ],alerts:["Não utilizar abaixo de 1 ano; entre 1 e 2 anos, somente após avaliação individual.","O esquema pode mudar para larva migrans visceral."],sources:["Referência pediátrica, fev/2024, seção de antiparasitários","Plantão Prescrições, seção de anti-helmínticos"]},
  {id:"ciprofloxacino",name:"Ciprofloxacino",aliases:["cipro","quinolona","antibiótico","pseudomonas","pielonefrite"],use:"Infecções bacterianas selecionadas",tone:"blue",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:500,doseMax:500,interval:"a cada 12 h; duração conforme foco",maxDay:"1.000 mg/dia neste esquema",presentations:[{label:"Comprimido 500 mg",concentration:500,unit:"comprimido",note:"1 comprimido por dose"}]},
    {label:"EV — adulto",age:"Adulto",doseMin:400,doseMax:400,interval:"a cada 12 h; duração conforme foco",maxDay:"800 mg/dia neste esquema",presentations:[{label:"Bolsa 400 mg/200 mL",concentration:2,unit:"mL",note:"200 mL por dose; infundir em 1 h"}]},
    {label:"VO/EV — pediatria",age:"Pediatria",doseMin:10,doseMax:20,interval:"a cada 12 h",maxDose:750,maxDay:"1.000–1.200 mg/dia, conforme via",presentations:[{label:"Bolsa EV 2 mg/mL",concentration:2,unit:"mL",note:"infundir em 1 h"},{label:"Comprimido 500 mg",concentration:500,unit:"comprimido",note:"usar apenas quando a forma sólida for adequada"}]},
  ],alerts:["Em pediatria, reservar para indicações específicas em que o benefício supere o risco.","Separar a administração oral de antiácidos, ferro, cálcio e outros cátions."],sources:["Referência pediátrica, fev/2024, seção de antimicrobianos","Guia rápido de prescrições para o plantão, seções de infecção urinária e diarreia"]},
  {id:"levofloxacino",name:"Levofloxacino",aliases:["tavanic","quinolona","antibiótico","pneumonia","pielonefrite"],use:"Infecções bacterianas selecionadas",tone:"blue",regimens:[
    {label:"VO/EV — adulto 500 mg",age:"Adulto",doseMin:500,doseMax:500,interval:"a cada 24 h; duração conforme foco",maxDay:"500 mg/dia neste esquema",presentations:[{label:"Comprimido 500 mg",concentration:500,unit:"comprimido",note:"1 comprimido por dose"},{label:"Solução EV 5 mg/mL",concentration:5,unit:"mL",note:"100 mL por dose; infundir em pelo menos 1 h"}]},
    {label:"VO/EV — adulto 750 mg",age:"Adulto",doseMin:750,doseMax:750,interval:"a cada 24 h por 5–7 dias, conforme indicação",maxDay:"750 mg/dia",presentations:[{label:"Comprimido 750 mg",concentration:750,unit:"comprimido",note:"1 comprimido por dose"},{label:"Solução EV 5 mg/mL",concentration:5,unit:"mL",note:"150 mL por dose; infundir em 1–1,5 h"}]},
    {label:"VO/EV — pediatria",age:"Pediatria",doseMin:6,doseMax:10,interval:"a cada 12–24 h, conforme idade e indicação",maxDose:750,maxDay:"750 mg/dia",presentations:[{label:"Solução EV 5 mg/mL",concentration:5,unit:"mL",note:"infundir em 1–1,5 h"}]},
  ],alerts:["Em pediatria, reservar para indicações específicas.","Ajustar na disfunção renal e avaliar risco de QT longo, tendinopatia e efeitos neurológicos."],sources:["Referência pediátrica, fev/2024, seção de antimicrobianos","Guia rápido de prescrições para o plantão, seções respiratória e urinária"]},
  {id:"nitrofurantoina",name:"Nitrofurantoína",aliases:["macrodantina","antibiótico urinário","cistite","itu"],use:"Cistite não complicada",tone:"blue",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:100,doseMax:100,interval:"a cada 6–12 h por 5–7 dias, conforme formulação",maxDay:"400 mg/dia",presentations:[{label:"Cápsula 100 mg",concentration:100,unit:"comprimido",note:"1 cápsula por dose"}]},
  ],alerts:["Não usar para pielonefrite ou suspeita de infecção sistêmica.","Evitar quando a função renal não permitir concentração urinária adequada."],sources:["Plantão Prescrições, seção de infecção urinária"]},
  {id:"fosfomicina",name:"Fosfomicina trometamol",aliases:["monuril","antibiótico urinário","cistite","itu"],use:"Cistite não complicada em indicação selecionada",tone:"blue",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:3000,doseMax:3000,interval:"dose única",maxDose:3000,presentations:[{label:"Envelope 3 g",concentration:3000,unit:"sachê",note:"dissolver o conteúdo em água e administrar imediatamente"}]},
  ],alerts:["Não usar como tratamento isolado de pielonefrite ou sepse urinária."],sources:["Guia rápido de prescrições para o plantão, seção de infecção urinária"]},
  {id:"oseltamivir",name:"Oseltamivir",aliases:["tamiflu","antiviral","influenza","gripe"],use:"Tratamento de influenza",tone:"violet",regimens:[
    {label:"VO — adulto e >40 kg",age:"Adulto",doseMin:75,doseMax:75,interval:"a cada 12 h por 5 dias",maxDay:"150 mg/dia",presentations:[{label:"Cápsula 75 mg",concentration:75,unit:"comprimido",note:"1 cápsula por dose"}]},
    {label:"VO — RN >40 semanas",age:"Pediatria",doseMin:3,doseMax:3,interval:"a cada 12 h por 5 dias",presentations:[{label:"Solução extemporânea 15 mg/mL",concentration:15,unit:"mL",note:"cápsula de 30 mg em 2 mL, 45 mg em 3 mL ou 75 mg em 5 mL de água"}]},
    {label:"VO — 9 a 11 meses",age:"Pediatria",doseMin:3.5,doseMax:3.5,interval:"a cada 12 h por 5 dias",presentations:[{label:"Solução extemporânea 15 mg/mL",concentration:15,unit:"mL",note:"preparar imediatamente antes do uso"}]},
  ],alerts:["Prematuros usam dose por idade pós-menstrual específica.","Ajustar na disfunção renal."],sources:["Ministério da Saúde — Guia de manejo e tratamento de influenza, 2023","Referência pediátrica, fev/2024, seção de antivirais"],referenceUrl:"https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/influenza/guia-de-manejo-e-tratamento-de-influenza-2023"},
  {id:"ampicilina-sulbactam",name:"Ampicilina + sulbactam",aliases:["unasyn","betalactâmico","antibiótico","aspiração","intra-abdominal"],use:"Infecções bacterianas sensíveis com indicação parenteral",tone:"blue",regimens:[
    {label:"EV — adulto",age:"Adulto",doseMin:1500,doseMax:3000,interval:"a cada 6–8 h",maxDay:"8 g/dia de ampicilina",presentations:[{label:"Frasco 1,5 g",concentration:250,unit:"mL",note:"reconstituir e rediluir para 30 mg/mL; infundir em 30–40 min"}]},
    {label:"EV — pediatria",age:"Pediatria",doseMin:50,doseMax:50,interval:"a cada 6 h",maxDose:2000,maxDay:"8 g/dia de ampicilina",presentations:[{label:"Solução reconstituída 250 mg/mL",concentration:250,unit:"mL",note:"rediluir para 30 mg/mL; infundir em 30–40 min"}],note:"Equivale a 200 mg/kg/dia de ampicilina divididos em 4 doses."},
  ],alerts:["Cálculo e teto expressos pelo componente ampicilina.","Ajustar o intervalo na disfunção renal."],sources:["Referência pediátrica, fev/2024, seção de antimicrobianos","Guia rápido de prescrições para o plantão, seções hospitalares"]},
  {id:"cefepima",name:"Cefepima",aliases:["maxcef","cefalosporina","antibiótico","pseudomonas","neutropenia febril"],use:"Infecções hospitalares por gram-negativos sensíveis",tone:"blue",regimens:[
    {label:"EV — adulto",age:"Adulto",doseMin:1000,doseMax:2000,interval:"a cada 8–12 h, conforme gravidade",maxDose:2000,maxDay:"6 g/dia",presentations:[{label:"Frasco-ampola 1 g",concentration:100,unit:"mL",note:"rediluir em 25–100 mL de SF 0,9% ou SG 5%; infundir em 30 min"}]},
    {label:"EV — pediatria",age:"Pediatria",doseMin:50,doseMax:50,interval:"a cada 8 h",maxDose:2000,maxDay:"6 g/dia",presentations:[{label:"Solução reconstituída 100 mg/mL",concentration:100,unit:"mL",note:"rediluir e infundir em 30 min"}]},
  ],alerts:["Ajustar obrigatoriamente na disfunção renal; acúmulo aumenta risco de neurotoxicidade."],sources:["Protocolo assistencial HC-UFMG/Ebserh","Guia rápido de prescrições para o plantão, seção hospitalar"],referenceUrl:"https://www.gov.br/hubrasil/pt-br/hospitais-universitarios/regiao-sudeste/hc-ufmg/saude/protocolos-assistenciais-hc-ufmg-ebserh/PR_005_Diagnostico_tratamento_infeccao_associada_cateter_intravascular_V05.pdf"},
  {id:"cefuroxima",name:"Cefuroxima",aliases:["zinnat","cefalosporina","antibiótico","otite","sinusite"],use:"Infecções bacterianas sensíveis",tone:"blue",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:500,doseMax:500,interval:"a cada 12 h; duração conforme foco",maxDay:"1 g/dia neste esquema",presentations:[{label:"Comprimido 500 mg",concentration:500,unit:"comprimido",note:"1 comprimido por dose"}]},
    {label:"VO — pediatria",age:"Pediatria",doseMin:15,doseMax:15,interval:"a cada 12 h",maxDose:500,maxDay:"1 g/dia",presentations:[{label:"Suspensão 250 mg/5 mL",concentration:50,unit:"mL",note:"reconstituir até a marca e agitar"}]},
    {label:"EV — pediatria",age:"Pediatria",doseMin:25,doseMax:50,interval:"a cada 8 h",maxDay:"6 g/dia",presentations:[{label:"Solução reconstituída 125 mg/mL",concentration:125,unit:"mL",note:"frasco 750 mg + 6 mL de AD; rediluir e infundir em 30 min"}]},
  ],alerts:["A dose muda entre via oral e parenteral.","Ajustar na disfunção renal."],sources:["Referência pediátrica, fev/2024, seção de antimicrobianos","Guia rápido de prescrições para o plantão, seções respiratória e urinária"]},
  {id:"claritromicina",name:"Claritromicina",aliases:["klaricid","macrolídeo","antibiótico","pneumonia","atípicos"],use:"Infecções bacterianas com indicação de macrolídeo",tone:"blue",regimens:[
    {label:"VO — adulto",age:"Adulto",doseMin:500,doseMax:500,interval:"a cada 12 h por 5–10 dias, conforme indicação",maxDay:"1 g/dia",presentations:[{label:"Comprimido 500 mg",concentration:500,unit:"comprimido",note:"1 comprimido por dose"}]},
    {label:"VO/EV — pediatria",age:"Pediatria",doseMin:7.5,doseMax:7.5,interval:"a cada 12 h",maxDose:500,maxDay:"1 g/dia",presentations:[{label:"Suspensão 250 mg/5 mL",concentration:50,unit:"mL",note:"reconstituir até a marca e agitar"},{label:"Solução EV 50 mg/mL",concentration:50,unit:"mL",note:"rediluir para 2 mg/mL e infundir em 1 h"}]},
  ],alerts:["Revisar interações por inibição do CYP3A4 e risco de prolongamento de QT."],sources:["Referência pediátrica, fev/2024, seção de antimicrobianos","Guia rápido de prescrições para o plantão, seção respiratória"]},
  {id:"oxacilina",name:"Oxacilina",aliases:["penicilina antiestafilocócica","antibiótico","mssa","celulite","bacteremia"],use:"Infecções por estafilococos sensíveis à oxacilina",tone:"blue",regimens:[
    {label:"EV — adulto",age:"Adulto",doseMin:2000,doseMax:2000,interval:"a cada 4 h",maxDay:"12 g/dia",presentations:[{label:"Solução reconstituída 100 mg/mL",concentration:100,unit:"mL",note:"rediluir para 10 mg/mL e infundir em 1 h"}]},
    {label:"EV — pediatria",age:"Pediatria",doseMin:25,doseMax:50,interval:"a cada 6 h",maxDose:2000,maxDay:"12 g/dia",presentations:[{label:"Solução reconstituída 100 mg/mL",concentration:100,unit:"mL",note:"rediluir para 10 mg/mL e infundir em 1 h"}]},
  ],alerts:["Confirmar sensibilidade à oxacilina; não cobre MRSA.","Monitorar função hepática e eletrólitos em cursos prolongados."],sources:["Referência pediátrica, fev/2024, seção de antimicrobianos","Protocolo assistencial HC-UFMG/Ebserh"]},
  {id:"piperacilina-tazobactam",name:"Piperacilina + tazobactam",aliases:["tazocin","antibiótico","pseudomonas","sepse","hospitalar"],use:"Infecções graves por microrganismos sensíveis",tone:"blue",regimens:[
    {label:"EV — adulto",age:"Adulto",doseMin:4500,doseMax:4500,interval:"a cada 6–8 h",maxDay:"18 g de piperacilina + 2,25 g de tazobactam",presentations:[{label:"Frasco 4 g + 500 mg",concentration:200,unit:"mL",note:"reconstituir e rediluir em solução compatível; infundir conforme protocolo"}]},
    {label:"EV — pediatria",age:"Pediatria",doseMin:75,doseMax:100,interval:"a cada 6 h",maxDose:4000,maxDay:"16 g/dia de piperacilina",presentations:[{label:"Solução 200 mg/mL de piperacilina",concentration:200,unit:"mL",note:"rediluir para 20–200 mg/mL e infundir em cerca de 1 h"}]},
  ],alerts:["Cálculo expresso pelo componente piperacilina.","Ajustar na disfunção renal e considerar maior risco renal quando associada à vancomicina."],sources:["Formulário Terapêutico Distrital — SES-DF","Protocolo pediátrico HC-UFMG/Ebserh"],referenceUrl:"https://www.saude.df.gov.br/documents/37101/531683/Piperacilina-Tazobactam.pdf/"},
  {id:"vancomicina",name:"Vancomicina",aliases:["glicopeptídeo","antibiótico","mrsa","bacteremia","meningite"],use:"Infecções graves por gram-positivos sensíveis",tone:"violet",regimens:[
    {label:"EV — adulto",age:"Adulto",weightBased:true,doseMin:15,doseMax:20,interval:"a cada 8–12 h, guiada por monitorização",maxDose:2000,maxDay:"definida por alvo farmacocinético e função renal",presentations:[{label:"Solução reconstituída 50 mg/mL",concentration:50,unit:"mL",note:"rediluir para 2,5–5 mg/mL e infundir em pelo menos 1 h"}]},
    {label:"EV — pediatria",age:"Pediatria",doseMin:10,doseMax:15,interval:"a cada 6 h",maxDose:2000,maxDay:"40–60 mg/kg/dia",presentations:[{label:"Solução reconstituída 50 mg/mL",concentration:50,unit:"mL",note:"rediluir para 2,5–5 mg/mL e infundir em pelo menos 1 h"}]},
  ],alerts:["Ajustar por função renal e monitorização farmacocinética; dose empírica não substitui AUC/nível quando indicado.","Infusão rápida aumenta risco de reação relacionada à infusão."],sources:["Referência pediátrica, fev/2024, seção de antimicrobianos","Protocolo assistencial HC-UFTM/Ebserh"]},
  {id:"amicacina",name:"Amicacina",aliases:["aminoglicosídeo","antibiótico","gram-negativos","pseudomonas"],use:"Infecções graves por gram-negativos sensíveis",tone:"violet",regimens:[
    {label:"EV — adulto",age:"Adulto",weightBased:true,doseMin:15,doseMax:15,interval:"a cada 24 h",maxDay:"1,5 g/dia",presentations:[{label:"Ampola 50 mg/mL",concentration:50,unit:"mL",note:"rediluir para cerca de 5–10 mg/mL e infundir em 1–2 h"}]},
    {label:"EV — pediatria",age:"Pediatria",doseMin:15,doseMax:15,interval:"a cada 24 h ou fracionada conforme idade",maxDose:1500,maxDay:"1,5 g/dia",presentations:[{label:"Ampola 50 mg/mL",concentration:50,unit:"mL",note:"rediluir para 5–10 mg/mL em SF 0,9% ou AD; infundir em 1–2 h"}]},
  ],alerts:["Ajustar por função renal e monitorizar níveis quando indicado.","Risco de nefrotoxicidade e ototoxicidade."],sources:["Referência pediátrica, fev/2024, seção de antimicrobianos","Protocolo assistencial HC-UFMG/Ebserh"]},
  {id:"gentamicina",name:"Gentamicina",aliases:["aminoglicosídeo","antibiótico","gram-negativos","sinergia"],use:"Infecções por gram-negativos e esquemas de sinergia",tone:"violet",regimens:[
    {label:"EV — adulto",age:"Adulto",weightBased:true,doseMin:5,doseMax:7,interval:"a cada 24 h, conforme indicação",maxDay:"Dose máxima individualizada por peso, função renal e níveis",presentations:[{label:"Ampola 40 mg/mL",concentration:40,unit:"mL",note:"rediluir para cerca de 10 mg/mL e infundir em 30–60 min"}]},
    {label:"EV — pediatria",age:"Pediatria",doseMin:5,doseMax:7,interval:"a cada 24 h ou fracionada conforme idade",maxDose:500,maxDay:"500 mg/dia",presentations:[{label:"Ampola 20 mg/mL",concentration:20,unit:"mL",note:"rediluir para 10 mg/mL em SF 0,9%; infundir em 30 min"},{label:"Ampola 40 mg/mL",concentration:40,unit:"mL",note:"rediluir para 10 mg/mL em SF 0,9%; infundir em 30 min"}]},
  ],alerts:["Neonatos exigem intervalo específico por idade gestacional e cronológica.","Monitorizar função renal e níveis quando indicado."],sources:["Referência pediátrica, fev/2024, seção de antimicrobianos","Protocolo assistencial HC-UFMG/Ebserh"]},
  {id:"aciclovir",name:"Aciclovir",aliases:["zovirax","antiviral","herpes","varicela","encefalite herpética"],use:"Infecções por herpes-vírus",tone:"violet",regimens:[
    {label:"VO — adulto, varicela",age:"Adulto",doseMin:800,doseMax:800,interval:"5 vezes ao dia por 7 dias",maxDay:"4 g/dia neste esquema",presentations:[{label:"Comprimido 400 mg",concentration:400,unit:"comprimido",note:"2 comprimidos por dose"},{label:"Comprimido 200 mg",concentration:200,unit:"comprimido",note:"4 comprimidos por dose"}]},
    {label:"VO — pediatria, varicela",age:"Pediatria",doseMin:20,doseMax:20,interval:"5 vezes ao dia por 5 dias",maxDose:800,maxDay:"4 g/dia",presentations:[{label:"Comprimido 200 mg",concentration:200,unit:"comprimido",note:"usar quando a forma sólida for adequada"}]},
    {label:"EV — pediatria, grave",age:"Pediatria",doseMin:10,doseMax:10,interval:"a cada 8 h por 7–14 dias",presentations:[{label:"Solução reconstituída 25 mg/mL",concentration:25,unit:"mL",note:"frasco 250 mg + 10 mL de AD; rediluir e infundir em 1 h"}],note:"Dose máxima não estabelecida de forma universal; depende da indicação e função renal."},
  ],alerts:["Garantir hidratação e ajustar na disfunção renal.","Encefalite, herpes neonatal e imunossupressão utilizam esquemas próprios."],sources:["Ministério da Saúde — tratamento do herpes","Referência pediátrica, fev/2024, seção de antivirais"],referenceUrl:"https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/h/herpes/tratamento"},
  {id:"midazolam",name:"Midazolam",aliases:["dormonid","benzodiazepínico","sedação","convulsão","intubação"],use:"Sedação, indução e crise convulsiva",tone:"violet",regimens:[
    {label:"EV — adulto, indução",age:"Adulto",weightBased:true,doseMin:.2,doseMax:.3,interval:"bolus lento, dose única",presentations:[{label:"Ampola 5 mg/mL",concentration:5,unit:"mL",note:"administrar em bolus lento"}]},
    {label:"EV — pediatria, sedação",age:"Pediatria",doseMin:.1,doseMax:.4,interval:"dose única; titular à resposta",presentations:[{label:"Solução rediluída 1 mg/mL",concentration:1,unit:"mL",note:"ampola 5 mg/mL: 1 mL + 4 mL de AD"}],note:"Dose usual de 0,2 mg/kg; faixa conforme profundidade de sedação e condição clínica."},
    {label:"EV — pediatria, convulsão",age:"Pediatria",doseMin:.15,doseMax:.3,interval:"dose única; pode repetir uma vez se necessário",maxDose:10,presentations:[{label:"Solução rediluída 1 mg/mL",concentration:1,unit:"mL",note:"ampola 5 mg/mL: 1 mL + 4 mL de AD"}],note:"Teto de 5 mg se <40 kg e 10 mg se ≥40 kg."},
  ],alerts:["Pode causar apneia, depressão respiratória e hipotensão; não produz analgesia.","Em indução, preparar ventilação e monitorização antes da administração."],sources:["Referência pediátrica, fev/2024, seções de convulsão e intubação","Guia rápido de prescrições para o plantão, sequência rápida de intubação","Ministério da Saúde — orientação para intubação orotraqueal"],referenceUrl:"https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/c/covid-19/publicacoes-tecnicas/recomendacoes/orientacoes-sobre-intubacao-orotraqueal-em-pacientes-com-covid-19"},
  {id:"diazepam",name:"Diazepam",aliases:["valium","benzodiazepínico","convulsão","estado de mal epiléptico"],use:"Interrupção de crise convulsiva",tone:"violet",regimens:[
    {label:"EV — adulto, convulsão",age:"Adulto",doseMin:10,doseMax:10,interval:"dose inicial; administrar a 2–5 mg/min",maxDay:"40 mg no atendimento agudo",presentations:[{label:"Ampola 5 mg/mL",concentration:5,unit:"mL",note:"administrar puro, lentamente"}]},
    {label:"EV — pediatria, convulsão",age:"Pediatria",doseMin:.2,doseMax:.5,interval:"dose inicial, lentamente",maxDose:10,presentations:[{label:"Ampola 5 mg/mL",concentration:5,unit:"mL",note:"administrar puro, lentamente"}]},
    {label:"Retal — pediatria, convulsão",age:"Pediatria",doseMin:.5,doseMax:.5,interval:"dose inicial",maxDose:20,presentations:[{label:"Solução 5 mg/mL",concentration:5,unit:"mL",note:"volume da solução por dose"}]},
  ],alerts:["Monitorizar ventilação, nível de consciência e pressão arterial.","A absorção IM é irregular; preferir a via definida para o cenário agudo."],sources:["Referência pediátrica, fev/2024, seção de convulsão","Plantão Prescrições, seção de estado de mal epiléptico"]},
  {id:"fenitoina",name:"Fenitoína",aliases:["hidantal","anticonvulsivante","convulsão","estado de mal epiléptico"],use:"Carga e manutenção anticonvulsivante",tone:"blue",regimens:[
    {label:"EV — adulto, ataque",age:"Adulto",weightBased:true,doseMin:15,doseMax:20,interval:"dose de ataque; velocidade máxima 50 mg/min",maxDose:1500,presentations:[{label:"Ampola 50 mg/mL",concentration:50,unit:"mL",note:"diluir somente em SF 0,9%; monitorizar ECG e pressão"}]},
    {label:"EV — pediatria, ataque",age:"Pediatria",doseMin:15,doseMax:20,interval:"dose de ataque em 20–30 min",maxDose:1500,presentations:[{label:"Solução rediluída 10 mg/mL",concentration:10,unit:"mL",note:"1 mL da ampola 50 mg/mL + 4 mL de SF 0,9%; máximo 50 mg/min"}]},
    {label:"EV — pediatria, manutenção",age:"Pediatria",doseMin:4,doseMax:10,interval:"por dia, dividido a cada 8 h; iniciar 8–12 h após a carga",maxDay:"300–500 mg/dia",presentations:[{label:"Ampola 50 mg/mL",concentration:50,unit:"mL",note:"dividir o volume diário em 3 administrações"}],note:"O resultado calculado corresponde à dose diária; dividir em três doses."},
  ],alerts:["Exige monitorização cardíaca e de pressão durante a carga EV.","Não diluir em solução glicosada; há risco de precipitação."],sources:["Referência pediátrica, fev/2024, seção de anticonvulsivantes","Plantão Prescrições, seção de estado de mal epiléptico"]},
  {id:"fenobarbital",name:"Fenobarbital",aliases:["gardenal","barbitúrico","anticonvulsivante","estado de mal epiléptico"],use:"Carga e manutenção anticonvulsivante",tone:"blue",regimens:[
    {label:"EV — adulto, ataque",age:"Adulto",weightBased:true,doseMin:10,doseMax:20,interval:"dose de ataque; administrar a 50–75 mg/min",presentations:[{label:"Ampola 100 mg/mL",concentration:100,unit:"mL",note:"administrar lentamente com monitorização"}]},
    {label:"EV — pediatria, ataque",age:"Pediatria",doseMin:10,doseMax:20,interval:"dose de ataque EV lenta",presentations:[{label:"Solução rediluída 10 mg/mL",concentration:10,unit:"mL",note:"1 mL da ampola 100 mg/mL + 9 mL de AD"}]},
    {label:"VO/EV — pediatria, manutenção",age:"Pediatria",doseMin:3,doseMax:5,interval:"por dia, em 1–2 administrações",maxDay:"100–200 mg/dia",presentations:[{label:"Solução 40 mg/mL",concentration:40,unit:"mL",note:"resultado é o volume diário; dividir se prescrito a cada 12 h"}],note:"O resultado calculado corresponde à dose diária."},
  ],alerts:["Pode causar depressão respiratória, hipotensão e sedação profunda; monitorizar durante a carga.","Somar doses de ataque antes de repetir para evitar acúmulo inadvertido."],sources:["Referência pediátrica, fev/2024, seção de anticonvulsivantes","Plantão Prescrições, seção de estado de mal epiléptico"]},
  {id:"levetiracetam",name:"Levetiracetam",aliases:["keppra","anticonvulsivante","convulsão","epilepsia"],use:"Carga e manutenção anticonvulsivante",tone:"blue",regimens:[
    {label:"EV — adulto, ataque",age:"Adulto",weightBased:true,doseMin:20,doseMax:20,interval:"dose de ataque em 5–15 min",presentations:[{label:"Solução injetável 100 mg/mL",concentration:100,unit:"mL",note:"rediluir em solução compatível para infusão"}]},
    {label:"VO — adulto, manutenção",age:"Adulto",doseMin:500,doseMax:500,interval:"a cada 12 h; titular conforme resposta",maxDay:"3.000 mg/dia",presentations:[{label:"Comprimido 500 mg",concentration:500,unit:"comprimido",note:"1 comprimido por dose"},{label:"Solução oral 100 mg/mL",concentration:100,unit:"mL",note:"5 mL por dose"}]},
    {label:"VO/EV — pediatria, manutenção",age:"Pediatria",doseMin:20,doseMax:30,interval:"a cada 12 h",maxDose:1500,maxDay:"60 mg/kg/dia ou 3.000 mg/dia",presentations:[{label:"Solução oral ou injetável 100 mg/mL",concentration:100,unit:"mL",note:"via e diluição conforme apresentação escolhida"}]},
  ],alerts:["Ajustar pela função renal.","Observar alterações de comportamento, irritabilidade e sintomas depressivos ou psicóticos."],sources:["Referência pediátrica, fev/2024, seção de anticonvulsivantes","Plantão Prescrições, seção de estado de mal epiléptico"]},
  {id:"cetamina",name:"Cetamina",aliases:["quetamina","ketamina","ketalar","sedação","analgesia","intubação"],use:"Indução, sedação e analgesia",tone:"coral",regimens:[
    {label:"EV — adulto, indução",age:"Adulto",weightBased:true,doseMin:2,doseMax:2,interval:"bolus lento, dose única",presentations:[{label:"Ampola 50 mg/mL",concentration:50,unit:"mL",note:"administrar em bolus lento"}]},
    {label:"EV — pediatria, indução",age:"Pediatria",doseMin:1,doseMax:4,interval:"dose única; titular à resposta",presentations:[{label:"Solução rediluída 10 mg/mL",concentration:10,unit:"mL",note:"ampola 50 mg/mL: 1 mL + 4 mL de AD"}]},
  ],alerts:["Pode aumentar secreções e causar laringoespasmo ou reações de emergência.","Em choque prolongado com depleção de catecolaminas, pode ocorrer depressão cardiovascular."],sources:["Referência pediátrica, fev/2024, seção de intubação","Guia rápido de prescrições para o plantão, sequência rápida de intubação","Ministério da Saúde — orientação para intubação orotraqueal"],referenceUrl:"https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/c/covid-19/publicacoes-tecnicas/recomendacoes/orientacoes-sobre-intubacao-orotraqueal-em-pacientes-com-covid-19"},
  {id:"etomidato",name:"Etomidato",aliases:["hypnomidate","sedação","indução","intubação"],use:"Indução para intubação",tone:"violet",regimens:[
    {label:"EV — adulto, indução",age:"Adulto",weightBased:true,doseMin:.3,doseMax:.3,interval:"bolus lento, dose única",presentations:[{label:"Ampola 2 mg/mL",concentration:2,unit:"mL",note:"administrar em bolus lento"}]},
    {label:"EV — pediatria, indução",age:"Pediatria",doseMin:.2,doseMax:.4,interval:"bolus lento, dose única",presentations:[{label:"Ampola 2 mg/mL",concentration:2,unit:"mL",note:"volume por dose"}]},
  ],alerts:["Evitar como primeira escolha em sepse ou choque séptico pela supressão transitória da síntese de cortisol.","Pode provocar mioclonia, náuseas e vômitos; não produz analgesia."],sources:["Referência pediátrica, fev/2024, seção de intubação","Guia rápido de prescrições para o plantão, sequência rápida de intubação","Ministério da Saúde — orientação para intubação orotraqueal"],referenceUrl:"https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/c/covid-19/publicacoes-tecnicas/recomendacoes/orientacoes-sobre-intubacao-orotraqueal-em-pacientes-com-covid-19"},
  {id:"propofol",name:"Propofol",aliases:["diprivan","sedação","indução","intubação"],use:"Indução e sedação profunda",tone:"violet",regimens:[
    {label:"EV — adulto, indução",age:"Adulto",weightBased:true,doseMin:1.5,doseMax:3,interval:"bolus lento, dose única",presentations:[{label:"Emulsão 10 mg/mL",concentration:10,unit:"mL",note:"administrar em bolus lento; titular ao efeito"}]},
    {label:"EV — pediatria, indução",age:"Pediatria",doseMin:1,doseMax:2,interval:"bolus lento, dose única",presentations:[{label:"Emulsão 10 mg/mL",concentration:10,unit:"mL",note:"volume por dose"}]},
  ],alerts:["Pode causar hipotensão intensa, apneia e depressão cardiovascular; reduzir ou evitar na instabilidade hemodinâmica.","Não produz analgesia."],sources:["Referência pediátrica, fev/2024, seção de intubação","Guia rápido de prescrições para o plantão, sequência rápida de intubação","Ministério da Saúde — orientação para intubação orotraqueal"],referenceUrl:"https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/c/covid-19/publicacoes-tecnicas/recomendacoes/orientacoes-sobre-intubacao-orotraqueal-em-pacientes-com-covid-19"},
  {id:"rocuronio",name:"Rocurônio",aliases:["esmeron","bloqueador neuromuscular","paralisante","intubação"],use:"Bloqueio neuromuscular para intubação",tone:"amber",regimens:[
    {label:"EV — adulto, sequência rápida",age:"Adulto",weightBased:true,doseMin:1.2,doseMax:1.2,interval:"bolus lento, dose única",presentations:[{label:"Ampola 10 mg/mL",concentration:10,unit:"mL",note:"pode ser administrado sem diluição"}]},
    {label:"EV — pediatria, intubação",age:"Pediatria",doseMin:.6,doseMax:1.2,interval:"bolus lento, dose única",presentations:[{label:"Ampola 10 mg/mL",concentration:10,unit:"mL",note:"puro ou diluído para 5 mg/mL; 1 mg/kg é a dose preferencial descrita"}]},
  ],alerts:["Provoca paralisia sem sedação, amnésia ou analgesia: administrar somente após indução adequada.","Assegurar ventilação e sedação contínua; o bloqueio pode durar 30–60 min."],sources:["Referência pediátrica, fev/2024, seção de intubação","Guia rápido de prescrições para o plantão, sequência rápida de intubação","Ministério da Saúde — orientação para intubação orotraqueal"],referenceUrl:"https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/c/covid-19/publicacoes-tecnicas/recomendacoes/orientacoes-sobre-intubacao-orotraqueal-em-pacientes-com-covid-19"},
  {id:"succinilcolina",name:"Succinilcolina",aliases:["suxametônio","quelicin","bloqueador neuromuscular","paralisante","intubação"],use:"Bloqueio neuromuscular para sequência rápida",tone:"amber",regimens:[
    {label:"EV — adulto, sequência rápida",age:"Adulto",weightBased:true,doseMin:1.5,doseMax:1.5,interval:"bolus lento, dose única",presentations:[{label:"Solução rediluída 10 mg/mL",concentration:10,unit:"mL",note:"frasco 100 mg: diluir para volume total de 10 mL com AD"}]},
    {label:"EV — pediatria, RN e <6 meses",age:"Pediatria",doseMin:2,doseMax:3,interval:"bolus lento, dose única",presentations:[{label:"Solução rediluída 5 mg/mL",concentration:5,unit:"mL",note:"ampola 50 mg/mL: 1 mL + 9 mL de AD"}]},
    {label:"EV — pediatria, criança maior",age:"Pediatria",doseMin:1,doseMax:1.5,interval:"bolus lento, dose única",presentations:[{label:"Solução rediluída 5 mg/mL",concentration:5,unit:"mL",note:"ampola 50 mg/mL: 1 mL + 9 mL de AD"}]},
  ],alerts:["Provoca paralisia sem sedação, amnésia ou analgesia: administrar somente após indução adequada.","Contraindicada em hipercalemia, doença neuromuscular, rabdomiólise, grandes queimaduras e suscetibilidade à hipertermia maligna."],sources:["Referência pediátrica, fev/2024, seção de intubação","Guia rápido de prescrições para o plantão, sequência rápida de intubação","Ministério da Saúde — orientação para intubação orotraqueal"],referenceUrl:"https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/c/covid-19/publicacoes-tecnicas/recomendacoes/orientacoes-sobre-intubacao-orotraqueal-em-pacientes-com-covid-19"},
];

const fmt=(n:number,digits=2)=>n.toLocaleString("pt-BR",{maximumFractionDigits:digits});

function Calculator({med}:{med:Medication}){
  const[regimenIndex,setRegimenIndex]=useState(0);const[weight,setWeight]=useState("20");const[presentationIndex,setPresentationIndex]=useState(0);
  const regimen=med.regimens[regimenIndex];const presentation=regimen.presentations[presentationIndex];const kg=Number(weight.replace(",","."));
  const weightBased=regimen.weightBased??regimen.age==="Pediatria";
  const calculated=weightBased&&regimen.doseMax>0&&Number.isFinite(kg)&&kg>0;
  let min=calculated?regimen.doseMin*kg:regimen.doseMin,max=calculated?regimen.doseMax*kg:regimen.doseMax;
  if(regimen.maxDose){min=Math.min(min,regimen.maxDose);max=Math.min(max,regimen.maxDose)}
  const values=presentation?{min:min/presentation.concentration,max:max/presentation.concentration}:null;
  const doseFormula=weightBased?`${fmt(regimen.doseMin)}${regimen.doseMax!==regimen.doseMin?`–${fmt(regimen.doseMax)}`:""} mg/kg/dose`:`${fmt(regimen.doseMin)}${regimen.doseMax!==regimen.doseMin?`–${fmt(regimen.doseMax)}`:""} mg/dose`;
  const converted=values&&presentation?`${fmt(values.min)}${values.max!==values.min?`–${fmt(values.max)}`:""} ${presentation.unit}${(["gota","comprimido","sachê","jato"].includes(presentation.unit)&&values.max!==1)?"s":""}`:"";
  const prescription=presentation&&regimen.doseMax>0?`${med.name} — ${regimen.label}: ${fmt(min)}${max!==min?`–${fmt(max)}`:""} mg (${converted}), ${regimen.interval}.${regimen.maxDay?` Máximo: ${regimen.maxDay}.`:""} Apresentação: ${presentation.label}.`:"";
  const setRegimen=(index:number)=>{setRegimenIndex(index);setPresentationIndex(0)};
  return <div className="medcalc">
    <div className="medcalc-controls"><label>Esquema<select value={regimenIndex} onChange={e=>setRegimen(Number(e.target.value))}>{med.regimens.map((r,i)=><option key={r.label} value={i}>{r.label}</option>)}</select></label>{weightBased&&regimen.doseMax>0&&<label>Peso (kg)<input inputMode="decimal" value={weight} onChange={e=>setWeight(e.target.value.replace(/[^0-9,.]/g,""))}/></label>}{regimen.presentations.length>0&&<label>Apresentação<select value={presentationIndex} onChange={e=>setPresentationIndex(Number(e.target.value))}>{regimen.presentations.map((p,i)=><option value={i} key={p.label}>{p.label}</option>)}</select></label>}</div>
    {regimen.doseMax>0?<div className="medresult"><small>DOSE CALCULADA</small><strong>{fmt(min)}{max!==min?`–${fmt(max)}`:""} <span>mg/dose</span></strong>{values&&<b>{fmt(values.min)}{values.max!==values.min?`–${fmt(values.max)}`:""} {presentation.unit}{(["gota","comprimido","sachê"].includes(presentation.unit))&&values.max!==1?"s":""}</b>}<p>{regimen.interval}{regimen.maxDay?` · máximo ${regimen.maxDay}`:""}</p>{presentation&&<em>{presentation.note}</em>}</div>:<div className="medresult text"><small>ESQUEMA POR FAIXA</small><strong>2 / 4 / 8 mg</strong><p>{regimen.note}</p></div>}
    {regimen.doseMax>0&&<div className="posology"><small>POSOLOGIA</small><dl><div><dt>Dose</dt><dd>{doseFormula}</dd></div><div><dt>Via</dt><dd>{regimen.label.split(" — ")[0]}</dd></div><div><dt>Frequência e duração</dt><dd>{regimen.interval}</dd></div>{(regimen.maxDay||regimen.maxDose)&&<div><dt>Dose máxima</dt><dd>{regimen.maxDay??`${fmt(regimen.maxDose!)} mg/dose`}</dd></div>}</dl>{prescription&&<button onClick={()=>navigator.clipboard?.writeText(prescription)}>Copiar prescrição pronta</button>}</div>}
    {regimen.note&&regimen.doseMax>0&&<p className="mednote">{regimen.note}</p>}
  </div>
}

export default function MedicationCatalog({initialQuery}:{initialQuery:string}){
  const[open,setOpen]=useState<string>("dipirona");const list=useMemo(()=>medications.filter(m=>!initialQuery||`${m.name} ${m.aliases.join(" ")} ${m.use}`.toLowerCase().includes(initialQuery.toLowerCase())),[initialQuery]);
  return <section className="medications" id="medicamentos"><div className="medications-head"><div><small>MEDICAMENTOS</small><h2>Calcule e converta sem sair da tela.</h2><p>Dose em mg e conversão automática para a apresentação selecionada.</p></div><b>{list.length} fichas encontradas</b></div>{list.length?<div className="medication-list">{list.map(m=><article className={`medication ${m.tone} ${open===m.id?"expanded":""}`} key={m.id}><button className="medication-summary" onClick={()=>setOpen(open===m.id?"":m.id)} aria-expanded={open===m.id}><div><small>{m.use}</small><h3>{m.name}</h3><p>{m.aliases.slice(0,3).join(" · ")}</p></div><span>{open===m.id?"−":"+"}</span></button>{open===m.id&&<div className="medication-body"><Calculator med={m}/><div className="meddetails"><div><small>ALERTAS CLÍNICOS</small>{m.alerts.map(a=><p key={a}>⚠ {a}</p>)}</div><div><small>REFERÊNCIAS CLÍNICAS</small>{m.sources.map(s=><p key={s}>{s}</p>)}{m.referenceUrl&&<a href={m.referenceUrl} target="_blank" rel="noreferrer">Consultar referência ↗</a>}</div></div></div>}</article>)}</div>:<div className="empty"><b>Nenhum medicamento encontrado.</b><span>Busque pelo princípio ativo, nome comercial ou indicação.</span></div>}<footer className="medication-status"><span>Catálogo clínico</span><p>{medications.length} medicamentos com cálculo e prescrição rápida.</p></footer></section>
}
