"use client";
import { useEffect, useMemo, useState } from "react";
import SignOutButton from "../sign-out-button";
import { createClient } from "../../utils/supabase/client";
import MedicationCatalog from "./medication-catalog";

type P={id:string;title:string;sub:string;age:"Adulto"|"Pediatria"|"Ambos";cat:"Emergência"|"Antibiótico"|"Infusão"|"Comum";tone:string;steps:[string,string][];alerts:string[];source:string;url:string;local?:boolean};
const data:P[]=[
{id:"anafilaxia",title:"Anafilaxia",sub:"Adrenalina IM é a primeira linha",age:"Ambos",cat:"Emergência",tone:"red",steps:[["Adulto","Adrenalina 1 mg/mL: 0,5 mg (0,5 mL) IM no vasto lateral da coxa."],["Pediatria","Adrenalina 1 mg/mL: 0,01 mg/kg (0,01 mL/kg) IM; máximo 0,3 mg."],["Repetição","Reavaliar e repetir a cada 5–15 minutos, se necessário."],["Suporte","Monitorização, oxigênio conforme necessidade, acesso IV/IO e cristaloide se choque."]],alerts:["Não atrasar adrenalina para administrar corticoide ou anti-histamínico.","Adrenalina IV exige ambiente monitorizado e protocolo específico."],source:"SES-DF — Manejo básico da anafilaxia, 2024",url:"https://www.saude.df.gov.br/documents/37101/0/Manejo%2Bbasico%2Bda%2Banafilaxia%2Bem%2Bambiente%2Bnao%2Bhospitalar%2Bpos%2Bvacina%C3%A7%C3%A3o%2B1.pdf/3f860189-d37e-3284-3851-aace186ae51e?t=1723740941632"},
{id:"dengue-a",title:"Dengue — Grupo A",sub:"Sem sinais de alarme ou condições especiais",age:"Ambos",cat:"Comum",tone:"amber",steps:[["Hidratação","Via oral: 60 mL/kg/dia; 1/3 com solução de reidratação oral e 2/3 com líquidos caseiros."],["Sintomas","Paracetamol ou dipirona conforme peso/idade, alergias e contraindicações."],["Seguimento","Orientar sinais de alarme e retorno no dia da melhora da febre ou no 5º dia da doença."]],alerts:["Evitar AAS, ibuprofeno e outros anti-inflamatórios.","Reclassificar se surgirem sinais de alarme, sangramento ou condição de risco."],source:"Ministério da Saúde — Dengue: diagnóstico e manejo clínico, 2024",url:"https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/dengue/dengue-diagnostico-e-manejo-clinico-adulto-e-crianca/view"},
{id:"dengue-c",title:"Dengue — sinais de alarme",sub:"Grupo C: reposição e reavaliação seriada",age:"Ambos",cat:"Emergência",tone:"red",steps:[["Expansão","SF 0,9%: 10 mL/kg IV em 2 horas; reavaliar sinais vitais, perfusão, diurese e hematócrito."],["Resposta","Após melhora, seguir fases de manutenção/redução conforme fluxograma do Ministério da Saúde."],["Monitorização","Hematócrito antes da expansão e a cada reavaliação; balanço hídrico rigoroso."]],alerts:["Choque ou deterioração clínica: manejar como Grupo D.","Cardiopatia, nefropatia e extremos de idade exigem individualização."],source:"Ministério da Saúde — Dengue: diagnóstico e manejo clínico, 2024",url:"https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/dengue/dengue-diagnostico-e-manejo-clinico-adulto-e-crianca/view"},
{id:"sepse",title:"Sepse — primeira hora",sub:"Checklist operacional para reconhecimento",age:"Ambos",cat:"Emergência",tone:"violet",steps:[["Coletas","Lactato, hemoculturas antes do antibiótico se isso não causar atraso e exames conforme foco."],["Antimicrobiano","Administrar precocemente; escolher conforme foco, epidemiologia e CCIH."],["Perfusão","Cristaloide em alíquotas com reavaliação; vasopressor se hipotensão persistente."]],alerts:["Em pediatria, reavaliar após cada alíquota.","Registrar alergias, culturas, horário e dose administrada."],source:"Modelo para adaptação ao protocolo institucional",url:"https://www.gov.br/anvisa/pt-br/assuntos/servicosdesaude/AntimicrobianosnaPrticaClnica_GuiaparaAPS.pdf",local:true},
{id:"pac",title:"Pneumonia comunitária",sub:"Esquema empírico inicial no adulto",age:"Adulto",cat:"Antibiótico",tone:"blue",steps:[["Estratificar","Gravidade, aspiração, risco de MRSA/Pseudomonas, alergias e função renal."],["Escolher","Aplicar o esquema da CCIH; registrar foco, início e prazo de reavaliação."],["Revisar","Em 48–72 h: culturas, descalonamento, troca para VO e duração total."]],alerts:["Não há esquema nacional único que substitua resistência e padronização locais."],source:"Anvisa — Antimicrobianos na prática clínica",url:"https://www.gov.br/anvisa/pt-br/assuntos/servicosdesaude/AntimicrobianosnaPrticaClnica_GuiaparaAPS.pdf",local:true},
{id:"itu",title:"Infecção urinária",sub:"Cistite, pielonefrite ou sepse urinária",age:"Adulto",cat:"Antibiótico",tone:"blue",steps:[["Classificar","Definir sítio; pesquisar gestação, obstrução, cateter e sepse."],["Coletar","Urocultura antes do antimicrobiano nos casos complicados, sem atrasar tratamento da instabilidade."],["Escolher","Considerar antibiograma local, função renal, alergias e exposição antimicrobiana recente."]],alerts:["Nitrofurantoína e fosfomicina não tratam pielonefrite.","Gestação e sexo masculino mudam investigação e tratamento."],source:"Anvisa — Antimicrobianos na prática clínica",url:"https://www.gov.br/anvisa/pt-br/assuntos/servicosdesaude/AntimicrobianosnaPrticaClnica_GuiaparaAPS.pdf",local:true},
{id:"atb-ped",title:"Antimicrobiano pediátrico",sub:"Barreira de segurança para cálculo por peso",age:"Pediatria",cat:"Antibiótico",tone:"blue",steps:[["Peso","Usar peso atual; conferir mg/kg/dose versus mg/kg/dia e dose máxima."],["Converter","Passar de mg para mL só após confirmar concentração/apresentação disponível."],["Checar","Indicação, intervalo, função renal, alergia e interação antes de assinar."]],alerts:["Não calcular por idade quando o protocolo exige peso.","Neonatos precisam de protocolo próprio."],source:"HC-UFMG/Ebserh — Síndromes infecciosas em pediatria, 2025",url:"https://www.gov.br/hubrasil/pt-br/hospitais-universitarios/regiao-sudeste/hc-ufmg/saude/protocolos-assistenciais-hc-ufmg-ebserh/PRT_UVS_390_Tratamento_principais_sindromes_infecciosas_pediatria_V01.pdf",local:true},
{id:"nora",title:"Noradrenalina",sub:"Preparo, acesso e titulação",age:"Adulto",cat:"Infusão",tone:"teal",steps:[["Diluição","Selecionar a concentração padronizada da instituição e identificar claramente em µg/mL."],["Titulação","Bomba de infusão, monitorização contínua e meta hemodinâmica prescrita."],["Acesso","Preferir acesso central; se periférico temporário, usar veia proximal e vigiar extravasamento."]],alerts:["Concentrações variam entre serviços: não misturar tabelas.","Corrigir hipovolemia e investigar a causa do choque."],source:"Modelo para padronização institucional",url:"https://www.gov.br/anvisa/pt-br/assuntos/servicosdesaude",local:true},
{id:"febre",title:"Dor e febre",sub:"Checklist antes do sintomático",age:"Ambos",cat:"Comum",tone:"amber",steps:[["Avaliar","Identificar causa provável, intensidade, via possível e sinais de gravidade."],["Prescrever","Escolher fármaco e dose conforme peso/idade, alergias, função hepática/renal e gestação."],["Reavaliar","Definir intervalo e limite diário; evitar duplicidade em combinações."]],alerts:["Suspeita de dengue: evitar AAS e anti-inflamatórios.","Febre em lactente jovem exige protocolo específico."],source:"Ministério da Saúde — Manejo clínico da dengue, 2024",url:"https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/dengue/dengue-diagnostico-e-manejo-clinico-adulto-e-crianca/view"},
{id:"eme-adulto",title:"Estado de mal epiléptico",sub:"Adulto — benzodiazepínico e segunda linha",age:"Adulto",cat:"Emergência",tone:"violet",steps:[["Primeira linha","Diazepam 10 mg IV lento (1–2 mg/min); interromper quando cessar. Repetir a cada 5–10 min, máximo 30 mg."],["Segunda linha","Fenitoína 15–20 mg/kg IV em SF 0,9%; velocidade máxima 50 mg/min. Considerar 5–10 mg/kg adicional se persistir."],["Refratário","Fenobarbital 10 mg/kg IV/IO lento; uma repetição conforme resposta e protocolo de via aérea."]],alerts:["Monitorizar ventilação, pressão e ECG; preparar suporte de via aérea.","Fenitoína não deve ser diluída em solução glicosada."],source:"SAMU-DF — Protocolos de Regulação Médica de Urgência",url:"https://www.saude.df.gov.br/documents/37101/0/Protocolos%2Bde%2BRegula%C3%A7%C3%A3o%2BM%C3%A9dica%2Bde%2BUrg%C3%AAncia%2Bdo%2BSAMU-%2BDF%2B192%2Be%2BCrit%C3%A9rios%2BM%C3%A9dicos%2Bde%2BDespacho%2Bde%2BViaturas%2BCM.pdf/10e76074-d445-7a0a-a6d8-2a7f65d4d91f?t=1717432207776"},
{id:"convulsao-ped",title:"Crise convulsiva",sub:"Pediatria — resgate por peso",age:"Pediatria",cat:"Emergência",tone:"violet",steps:[["Acesso IV/IO","Diazepam 0,2–0,5 mg/kg IV/IO lento; máximo 2 mg no RN, 5 mg em menores de 5 anos e 10 mg a partir de 5 anos. Reavaliar após 5 min."],["Sem acesso","Midazolam intranasal 0,3 mg/kg (solução 5 mg/mL), metade em cada narina; máximo 5 mg."],["Alternativa IM","Midazolam 0,2 mg/kg IM (solução 5 mg/mL); máximo 5 mg."]],alerts:["Checar glicemia capilar e tratar causa reversível.","Depressão respiratória: monitorização e material de ventilação disponíveis."],source:"SAMU-DF — Protocolos pediátricos de urgência",url:"https://www.saude.df.gov.br/documents/37101/0/Protocolos%2Bde%2BRegula%C3%A7%C3%A3o%2BM%C3%A9dica%2Bde%2BUrg%C3%AAncia%2Bdo%2BSAMU-%2BDF%2B192%2Be%2BCrit%C3%A9rios%2BM%C3%A9dicos%2Bde%2BDespacho%2Bde%2BViaturas.%2BPED.pdf/475a9405-50eb-be13-e9f1-356801c4eddb?t=1717432225608"},
{id:"asma-adulto",title:"Asma aguda",sub:"Adulto — broncodilatadores e corticoide",age:"Adulto",cat:"Emergência",tone:"teal",steps:[["Salbutamol","2,5–5 mg nebulizado ou 4–8 jatos de 100 µg com espaçador, a cada 20 min nas 3 primeiras doses."],["Ipratrópio","0,5 mg nebulizado a cada 20 min por 3 doses nos casos graves."],["Corticoide","Prednisona 40–60 mg VO/dia ou metilprednisolona 40–80 mg IV/dia se VO inviável."],["Refratária","Sulfato de magnésio 2 g IV em 20 min se grave/refratária."]],alerts:["Oxigênio titulado e reavaliação objetiva; fadiga ou hipercapnia exigem suporte avançado.","Evitar sedativos em insuficiência respiratória não intubada."],source:"SES-MG/FHEMIG — Protocolos clínicos e referências de urgência",url:"https://www.fhemig.mg.gov.br/acesso-rapido/protocolos-clinicos",local:true},
{id:"asma-ped",title:"Sibilância/asma aguda",sub:"Pediatria — tratamento inicial",age:"Pediatria",cat:"Emergência",tone:"teal",steps:[["Salbutamol","Aerossol 100 µg: 4–10 jatos com espaçador a cada 20 min por 3 doses; ou nebulização 0,15 mg/kg (mín. 2,5 mg; máx. 5 mg)."],["Ipratrópio","250 µg (<20 kg) ou 500 µg (≥20 kg) nebulizado a cada 20 min por 3 doses se grave."],["Corticoide","Prednisolona 1–2 mg/kg VO (máx. 40–60 mg) precocemente; usar via IV se VO inviável."],["Refratária","Sulfato de magnésio 25–50 mg/kg IV em 20–30 min; máximo 2 g."]],alerts:["Bronquiolite em lactentes não deve ser tratada automaticamente como asma.","Reavaliar frequência respiratória, esforço, ausculta, SpO₂ e resposta após cada ciclo."],source:"FHEMIG — Protocolos clínicos pediátricos",url:"https://www.fhemig.mg.gov.br/acesso-rapido/protocolos-clinicos",local:true},
{id:"hipoglicemia",title:"Hipoglicemia grave",sub:"Correção imediata e prevenção de recorrência",age:"Ambos",cat:"Emergência",tone:"amber",steps:[["Adulto IV","Glicose 25 g IV (50 mL de SG 50% ou equivalente diluído), com nova glicemia em 10–15 min."],["Pediatria IV","SG 10%: 2,5 mL/kg IV (250 mg/kg); reavaliar em 10–15 min e repetir conforme resposta."],["Sem acesso","Glucagon IM: adulto 1 mg; criança <25 kg, 0,5 mg; resposta pode ser limitada em jejum prolongado."],["Depois","Oferecer carboidrato de ação prolongada quando seguro e tratar a causa."]],alerts:["Evitar SG 50% não diluído em crianças pelo risco de lesão venosa e hiperosmolaridade.","Sulfonilureia pode causar recorrência prolongada e exigir observação/octreotida."],source:"Protocolos públicos de urgência e bulas aprovadas pela Anvisa",url:"https://consultas.anvisa.gov.br/#/bulario/",local:true},
{id:"hipercalemia",title:"Hipercalemia com risco",sub:"Estabilizar membrana, deslocar K⁺ e remover",age:"Adulto",cat:"Emergência",tone:"red",steps:[["Membrana","Gluconato de cálcio 10%: 10 mL IV em 2–5 min; repetir em 5–10 min se alterações de ECG persistirem."],["Deslocamento","Insulina regular 10 UI IV + glicose 25 g IV; monitorar glicemia por pelo menos 4–6 h."],["Beta-agonista","Salbutamol 10–20 mg nebulizado como adjuvante; não usar isoladamente."],["Remoção","Considerar diurético, resina/quelante e diálise conforme causa, função renal e gravidade."]],alerts:["Cálcio não reduz potássio: apenas estabiliza temporariamente o miocárdio.","Bicarbonato não é rotina; considerar sobretudo se acidose metabólica relevante."],source:"Diretrizes nefrológicas e protocolos hospitalares públicos — validar apresentação local",url:"https://www.gov.br/saude/pt-br",local:true},
{id:"opioide",title:"Intoxicação por opioide",sub:"Ventilação primeiro; naloxona titulada",age:"Ambos",cat:"Emergência",tone:"red",steps:[["Suporte","Abrir via aérea e ventilar com bolsa-válvula-máscara se necessário; oxigênio e monitorização."],["Adulto","Naloxona 0,04 mg IV, titulando 0,1–0,4 mg a cada 2–3 min até ventilação adequada; doses maiores se apneia grave."],["Pediatria","Naloxona 0,1 mg/kg IV/IM/IN em menores de 5 anos ou ≤20 kg; máximo inicial 2 mg."],["Recorrência","Repetir conforme resposta; considerar infusão se opioide de longa ação, com toxicologia/CIATox."]],alerts:["Objetivo é restaurar ventilação, não necessariamente despertar completamente.","A meia-vida da naloxona pode ser menor que a do opioide."],source:"Manual de Toxicologia Clínica — SMS São Paulo",url:"https://drive.prefeitura.sp.gov.br/cidade/secretarias/upload/saude/arquivos/manual_toxicologia_clinica-covisa-2017.pdf",local:true},
{id:"meningite-adulto",title:"Meningite bacteriana",sub:"Adulto — antimicrobiano empírico",age:"Adulto",cat:"Antibiótico",tone:"blue",steps:[["Esquema base","Ceftriaxona 2 g IV a cada 12 h + vancomicina 15–20 mg/kg IV a cada 8–12 h, com monitorização farmacocinética."],["Listeria","Adicionar ampicilina 2 g IV a cada 4 h se ≥50 anos, gestação, imunossupressão ou risco clínico."],["Dexametasona","10 mg IV a cada 6 h por 4 dias, iniciada antes ou junto da primeira dose, quando indicada."],["Coletas","Hemoculturas e líquor se seguro, sem atrasar antibiótico em paciente instável."]],alerts:["Ajustar à função renal, alergias e epidemiologia local.","Suspeita de meningococcemia exige precaução e notificação/profilaxia de contatos."],source:"Protocolos públicos brasileiros e PCDT — validar CCIH",url:"https://www.gov.br/saude/pt-br",local:true},
{id:"pac-dose",title:"Pneumonia comunitária — dose",sub:"Adulto internado, fora de UTI",age:"Adulto",cat:"Antibiótico",tone:"blue",steps:[["Opção usual","Ceftriaxona 1–2 g IV a cada 24 h + azitromicina 500 mg VO/IV a cada 24 h."],["Alternativa","Ampicilina-sulbactam 3 g IV a cada 6 h + azitromicina 500 mg a cada 24 h."],["Duração","Em geral, mínimo 5 dias e até estabilidade clínica; individualizar complicações e patógeno."],["Revisão","Reavaliar em 48–72 h para troca VO, descalonamento e diagnóstico alternativo."]],alerts:["UTI, aspiração, influenza, MRSA ou Pseudomonas mudam o esquema.","Aplicar função renal, alergias e antibiograma institucional."],source:"Anvisa — Antimicrobianos na prática clínica e protocolos Ebserh",url:"https://www.gov.br/anvisa/pt-br/assuntos/servicosdesaude/AntimicrobianosnaPrticaClnica_GuiaparaAPS.pdf",local:true},
{id:"pielo-dose",title:"Pielonefrite",sub:"Adulto — terapia empírica inicial",age:"Adulto",cat:"Antibiótico",tone:"blue",steps:[["Sem sepse","Ceftriaxona 1 g IV a cada 24 h enquanto internado; ajustar após cultura."],["Sepse/risco resistente","Escolher cobertura ampliada conforme antibiograma e CCIH; coletar urocultura e hemoculturas."],["Duração","Geralmente 7 dias com boa resposta e agente adequado; ampliar conforme fármaco, complicação e evolução."],["Desobstrução","Investigar cálculo/obstrução; infecção obstruída é urgência urológica."]],alerts:["Nitrofurantoína e fosfomicina não alcançam tecido renal adequadamente.","Gestação, homem e anomalia urológica são cenários complicados."],source:"Anvisa — Antimicrobianos na prática clínica",url:"https://www.gov.br/anvisa/pt-br/assuntos/servicosdesaude/AntimicrobianosnaPrticaClnica_GuiaparaAPS.pdf",local:true}
];
const cats=["Todos","Emergência","Antibiótico","Infusão","Comum"] as const, ages=["Todos","Adulto","Pediatria"] as const;
type V={name:string;range:string;weighted:boolean;unit:string;dilutions:{label:string;concentration:number;prep:string}[];warning:string};
const vaso:V[]=[
{name:"Noradrenalina",range:"0,05–1 µg/kg/min (titular)",weighted:true,unit:"µg/kg/min",dilutions:[{label:"Padrão",concentration:16,prep:"4 mg em volume final de 250 mL = 16 µg/mL"},{label:"Concentrada",concentration:32,prep:"8 mg em volume final de 250 mL = 32 µg/mL"}],warning:"Primeira escolha usual no choque distributivo. Preferir acesso central; periférico proximal pode ser ponte com vigilância frequente."},
{name:"Adrenalina",range:"0,01–0,5 µg/kg/min (titular)",weighted:true,unit:"µg/kg/min",dilutions:[{label:"Padrão",concentration:16,prep:"4 mg em volume final de 250 mL = 16 µg/mL"},{label:"Concentrada",concentration:32,prep:"8 mg em volume final de 250 mL = 32 µg/mL"}],warning:"Conferir indicação, glicemia, lactato, ritmo e perfusão. Não confundir infusão com concentração 1 mg/mL usada por outras vias."},
{name:"Dobutamina",range:"2–20 µg/kg/min (titular)",weighted:true,unit:"µg/kg/min",dilutions:[{label:"Padrão",concentration:1000,prep:"250 mg em volume final de 250 mL = 1.000 µg/mL"},{label:"Concentrada",concentration:2000,prep:"500 mg em volume final de 250 mL = 2.000 µg/mL"}],warning:"Inotrópico: pode causar taquiarritmia e hipotensão. Usar guiado por avaliação de baixo débito/perfusão."},
{name:"Dopamina",range:"2–20 µg/kg/min (titular)",weighted:true,unit:"µg/kg/min",dilutions:[{label:"Padrão",concentration:1600,prep:"400 mg em volume final de 250 mL = 1.600 µg/mL"},{label:"Concentrada",concentration:3200,prep:"800 mg em volume final de 250 mL = 3.200 µg/mL"}],warning:"Maior risco de arritmia; não é vasopressor de primeira escolha na maioria dos choques."},
{name:"Vasopressina",range:"0,01–0,04 UI/min (dose fixa)",weighted:false,unit:"UI/min",dilutions:[{label:"Padrão",concentration:.2,prep:"20 UI em volume final de 100 mL = 0,2 UI/mL"},{label:"Concentrada",concentration:.4,prep:"40 UI em volume final de 100 mL = 0,4 UI/mL"}],warning:"Dose não baseada em peso. Geralmente adjuvante à noradrenalina; doses altas aumentam risco isquêmico."},
{name:"Nitroprussiato",range:"0,3–10 µg/kg/min (titular)",weighted:true,unit:"µg/kg/min",dilutions:[{label:"Padrão",concentration:200,prep:"50 mg em volume final de 250 mL = 200 µg/mL"},{label:"Concentrada",concentration:400,prep:"50 mg em volume final de 125 mL = 400 µg/mL"}],warning:"Proteger da luz. Monitorização contínua; risco de toxicidade aumenta com dose alta, infusão prolongada e disfunção renal/hepática."}
];
function VasoCalculator(){const[drug,setDrug]=useState(0),[dil,setDil]=useState(0),[kg,setKg]=useState("70"),[dose,setDose]=useState("0.1");const v=vaso[drug],d=v.dilutions[dil];const nkg=Number(kg.replace(",",".")),nd=Number(dose.replace(",","."));const rate=Number.isFinite(nd)&&nd>=0&&(!v.weighted||(Number.isFinite(nkg)&&nkg>0))?(v.weighted?nd*nkg*60/d.concentration:nd*60/d.concentration):NaN;return <section className="vaso" id="vaso"><div className="vasotitle"><div><small>CALCULADORA DE BOMBA</small><h2>Drogas vasoativas</h2><p>Duas diluições usuais para conferência transparente. Selecione sempre a concentração realmente preparada.</p></div><b>mL/h = dose × peso × 60 ÷ concentração</b></div><div className="vasogrid"><div className="vasocontrol"><label>Fármaco<select value={drug} onChange={e=>{setDrug(Number(e.target.value));setDil(0);setDose(e.target.value==="4"?"0.03":"0.1")}}>{vaso.map((x,i)=><option value={i} key={x.name}>{x.name}</option>)}</select></label><div className="doseinputs">{v.weighted&&<label>Peso (kg)<input inputMode="decimal" value={kg} onChange={e=>setKg(e.target.value)}/></label>}<label>Dose ({v.unit})<input inputMode="decimal" value={dose} onChange={e=>setDose(e.target.value)}/></label></div><p className="range">Faixa usual: <b>{v.range}</b></p></div><div className="dilutions">{v.dilutions.map((x,i)=><button key={x.label} className={dil===i?"selected":""} onClick={()=>setDil(i)}><span>{x.label}</span><b>{x.prep}</b></button>)}</div><div className="result"><small>VELOCIDADE CALCULADA</small><strong>{Number.isFinite(rate)?rate.toLocaleString("pt-BR",{maximumFractionDigits:1}):"—"}<span> mL/h</span></strong><p>{d.prep}</p></div></div><div className="vasowarn"><b>⚠ Dupla checagem obrigatória</b><p>{v.warning} Este resultado é matemático e não valida indicação, dose, estabilidade, compatibilidade ou padronização local.</p></div></section>}
function ClinicalQuickCalc({protocol,weight,setWeight}:{protocol:P;weight:string;setWeight:(value:string)=>void}){
const[ageGroup,setAgeGroup]=useState("under5");const kg=Number(weight.replace(",","."));const valid=Number.isFinite(kg)&&kg>0;const f=(n:number,d=2)=>n.toLocaleString("pt-BR",{maximumFractionDigits:d});let title="",primary="",secondary="",prescription="";
if(protocol.id==="anafilaxia"){const mg=valid?Math.min(kg*.01,.3):0;title="Adrenalina IM pediátrica";primary=valid?`${f(mg)} mg = ${f(mg)} mL`:"Informe o peso";secondary="Solução 1 mg/mL · máximo 0,3 mg · repetir em 5–15 min se necessário";prescription=valid?`Adrenalina 1 mg/mL: ${f(mg)} mg (${f(mg)} mL) IM no vasto lateral da coxa.`:""}
else if(protocol.id==="dengue-a"){const total=valid?kg*60:0;title="Hidratação oral — 24 horas";primary=valid?`${f(total,0)} mL/dia`:"Informe o peso";secondary=valid?`${f(total/3,0)} mL de SRO + ${f(total*2/3,0)} mL de outros líquidos`:"60 mL/kg/dia";prescription=valid?`Hidratação VO: ${f(total,0)} mL/24 h, sendo ${f(total/3,0)} mL de SRO e ${f(total*2/3,0)} mL de líquidos caseiros.`:""}
else if(protocol.id==="dengue-c"){const volume=valid?kg*10:0;title="Expansão com SF 0,9%";primary=valid?`${f(volume,0)} mL em 2 h`:"Informe o peso";secondary=valid?`Bomba: ${f(volume/2,0)} mL/h · reavaliar após a expansão`:"10 mL/kg em 2 horas";prescription=valid?`SF 0,9%: ${f(volume,0)} mL IV em 2 horas (${f(volume/2,0)} mL/h).`:""}
else if(protocol.id==="convulsao-ped"){const cap=ageGroup==="rn"?2:ageGroup==="under5"?5:10;const diaMin=valid?Math.min(kg*.2,cap):0,diaMax=valid?Math.min(kg*.5,cap):0,midIN=valid?Math.min(kg*.3,5):0,midIM=valid?Math.min(kg*.2,5):0;title="Resgate anticonvulsivante";primary=valid?`Diazepam: ${f(diaMin)}–${f(diaMax)} mg (${f(diaMin/5)}–${f(diaMax/5)} mL)`:"Informe peso e faixa etária";secondary=valid?`Sem acesso: midazolam IN ${f(midIN)} mg (${f(midIN/5)} mL), metade em cada narina · IM ${f(midIM)} mg (${f(midIM/5)} mL)`:"Soluções de diazepam e midazolam: 5 mg/mL";prescription=valid?`Diazepam 5 mg/mL: ${f(diaMin)}–${f(diaMax)} mg (${f(diaMin/5)}–${f(diaMax/5)} mL) IV/IO lento. Sem acesso: midazolam 5 mg/mL ${f(midIN)} mg (${f(midIN/5)} mL) IN, metade em cada narina.`:""}
else if(protocol.id==="asma-ped"){const sal=valid?Math.min(Math.max(kg*.15,2.5),5):0,ipr=valid?(kg<20?250:500):0;title="Broncodilatadores — primeiro ciclo";primary=valid?`Salbutamol ${f(sal)} mg = ${f(sal/5)} mL`:"Informe o peso";secondary=valid?`Solução 5 mg/mL · nebulizar a cada 20 min por 3 doses · se grave: ipratrópio ${ipr} µg por dose`:"Salbutamol 0,15 mg/kg; mínimo 2,5 mg, máximo 5 mg";prescription=valid?`Salbutamol 5 mg/mL: ${f(sal)} mg (${f(sal/5)} mL) por nebulização, a cada 20 minutos por 3 doses. Se crise grave, associar ipratrópio ${ipr} µg por nebulização, a cada 20 minutos por 3 doses.`:""}
else if(protocol.id==="hipoglicemia"){const volume=valid?kg*2.5:0,glucagon=valid&&kg<25?.5:1;title="Correção pediátrica";primary=valid?`SG 10%: ${f(volume,1)} mL IV`:"Informe o peso";secondary=valid?`250 mg/kg · repetir glicemia em 10–15 min · sem acesso: glucagon ${f(glucagon,1)} mg IM`:"SG 10%: 2,5 mL/kg";prescription=valid?`SG 10%: ${f(volume,1)} mL IV. Reavaliar glicemia em 10–15 minutos. Se sem acesso venoso: glucagon ${f(glucagon,1)} mg IM.`:""}
else return protocol.age!=="Adulto"?<div className="weight"><label>Peso atual <small>usado nas doses por kg abaixo</small></label><div><input value={weight} onChange={e=>setWeight(e.target.value.replace(/[^0-9,.]/g,""))} placeholder="—"/><b>kg</b></div></div>:null;
return <div className="quickcalc"><div className="quickcalc-input"><label>Peso<input inputMode="decimal" value={weight} onChange={e=>setWeight(e.target.value.replace(/[^0-9,.]/g,""))}/><b>kg</b></label>{protocol.id==="convulsao-ped"&&<label className="agegroup">Faixa<select value={ageGroup} onChange={e=>setAgeGroup(e.target.value)}><option value="rn">Recém-nascido</option><option value="under5">Menor de 5 anos</option><option value="over5">5 anos ou mais</option></select></label>}<span>Cálculo automático</span></div><div className="quickcalc-result"><small>{title}</small><strong>{primary}</strong><p>{secondary}</p></div>{prescription&&<button onClick={()=>navigator.clipboard?.writeText(prescription)}>Copiar prescrição</button>}</div>}
export default function Home(){const[q,setQ]=useState("");const[cat,setCat]=useState<(typeof cats)[number]>("Todos");const[age,setAge]=useState<(typeof ages)[number]>("Todos");const[open,setOpen]=useState<P|null>(null);const[weight,setWeight]=useState("");const[isOwner,setIsOwner]=useState(false);const list=useMemo(()=>data.filter(p=>(!q||`${p.title} ${p.sub} ${p.cat}`.toLowerCase().includes(q.toLowerCase()))&&(cat==="Todos"||p.cat===cat)&&(age==="Todos"||p.age===age||p.age==="Ambos")),[q,cat,age]);
useEffect(()=>{createClient().auth.getUser().then(({data})=>setIsOwner(data.user?.app_metadata?.role==="owner"))},[]);
return <main><header><a className="brand" href="#top"><b>Rx</b><strong>Rx <span>Plantão</span></strong></a><div className="headright"><i/> Pronto para o plantão {isOwner&&<a className="ml-2 rounded bg-[#e5ece7] px-2.5 py-2 font-mono text-[9px] font-bold uppercase tracking-wide text-[#1f5845] no-underline" href="/admin">Painel</a>}<button aria-label="Ver checagem de segurança" onClick={()=>document.querySelector(".safety")?.scrollIntoView()}>i</button><SignOutButton/></div></header>
<section className="hero" id="top"><div><p className="eyebrow">Apoio à decisão no pronto-socorro</p><h1>O essencial, <em>sem perder tempo.</em></h1><p>Protocolos rápidos para adultos e pediatria, com alertas de segurança e fonte em cada conduta.</p></div><aside><b>Plantão</b><span>modo rápido</span></aside></section>
<section className="work"><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar condição, medicamento ou protocolo…"/><kbd>/</kbd></div><div className="filters"><nav>{ages.map(x=><button key={x} className={age===x?"on":""} onClick={()=>setAge(x)}>{x}</button>)}</nav><nav>{cats.map(x=><button key={x} className={cat===x?"on dark":""} onClick={()=>setCat(x)}>{x}</button>)}</nav></div>
<div className="sectiontitle"><div><small>PROTOCOLOS</small><h2>{list.length} atalhos disponíveis</h2></div><a href="#vaso">Abrir calculadora de bomba ↓</a></div><div className="grid">{list.map((p,i)=><button className={`card ${p.tone}`} key={p.id} onClick={()=>{setOpen(p);document.body.style.overflow="hidden"}}><div className="cardtop"><span>{String(i+1).padStart(2,"0")}</span><b>{p.age}</b></div><div><small>{p.cat}</small><h3>{p.title}</h3><p>{p.sub}</p></div><footer><span>{p.steps.length} etapas</span><i>→</i></footer></button>)}</div>{!list.length&&<div className="empty"><b>Nenhum protocolo encontrado.</b><span>Remova um filtro ou use um termo mais amplo.</span></div>}</section>
<MedicationCatalog initialQuery={q}/>
<VasoCalculator/>
<section className="safety"><b>!</b><div><small>BARREIRA DE SEGURANÇA</small><h2>Antes de assinar, pare por 10 segundos.</h2></div><ul><li>Paciente e peso corretos</li><li>Alergias e gestação</li><li>Função renal e hepática</li><li>Concentração e dose máxima</li></ul></section>
<div className="legal"><strong>Rx Plantão</strong><span>Ferramenta educacional de apoio. A decisão e a prescrição permanecem sob responsabilidade do profissional habilitado.</span></div>
{open&&<div className="backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setOpen(null);document.body.style.overflow=""}}}><article className="modal"><div className={`modalhead ${open.tone}`}><div><small>{open.cat} · {open.age}</small><h2>{open.title}</h2><p>{open.sub}</p></div><button aria-label="Fechar" onClick={()=>{setOpen(null);document.body.style.overflow=""}}>×</button></div><div className="modalbody"><ClinicalQuickCalc protocol={open} weight={weight} setWeight={setWeight}/><ol>{open.steps.map((s,i)=><li key={s[0]}><span>{i+1}</span><div><b>{s[0]}</b><p>{s[1]}</p></div></li>)}</ol><div className="alerts"><b>Alertas críticos</b>{open.alerts.map(x=><p key={x}>⚠ {x}</p>)}</div><div className="source"><div><small>Fonte primária</small><a href={open.url} target="_blank" rel="noreferrer">{open.source} ↗</a></div><span>Revisado em 18 ago 2026</span></div></div><div className="modalfoot"><button onClick={()=>{setOpen(null);document.body.style.overflow=""}}>Fechar protocolo</button></div></article></div>}</main>}
